---
title: "Data preparation"
author: "Julio Iturra"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output:
  bookdown::html_document2:
    number_sections: true
    toc: true
    toc_float:
        collapsed: false
    toc_depth: 2
    code_folding: "hide"
editor_options:
  chunk_output_type: console
---

# Setup

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE, 
                      cache = FALSE,
                      results = "hold")
options(scipen=999)
rm(list=ls())
options(knitr.kable.NA = '')
# .rs.restartR()
```

```{css, echo=FALSE}
# /* expandir el espacio del documento*/
body .main-container {
      max-width: 1600px !important;
      width: 1600px !important;
    }
#/* expandir width de la TOC*/
div.tocify {
    width: 22% !important;
    max-width: 331px !important;
    max-height: 102% !important;
}
```

**load packages**
```{r}
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,       # Manipulacion de datos 
               haven,       # importar datos en .dta o .sav
               sjmisc,      # descriptivos y frecuencias
               sjPlot,      # tablas, plots y descriptivos
               sjlabelled,
               summarytools,# resumen de dataframe
               knitr,       # tablas kable
               kableExtra,  # tablas kable personalizadas
               ggplot2,     # plots
               corrplot,    # plot correlacion
               survey,
               tibble
               )

```

# Ola 1

```{r}
options(scipen=999)
rm(list=ls())
df_wave01 <- haven::read_sav(file = here::here("input/data/original/Ola_1.sav"))
weight_wave01 <- haven::read_dta(file = here::here("input/data/proc/weight_w01.dta"))
table(df_wave01$ticket==weight_wave01$ticket)
table(df_wave01$ResponseId==weight_wave01$ResponseId)
weight_wave01$ticket <- NULL
# names(df_wave01)

#seleccionar ID proveniente de la variable ticket
df_wave01$folio_encuestado<- stringr::str_split(df_wave01$ticket,pattern = "_",simplify = T)[,1]
df_wave01 <- left_join(x = df_wave01,
                        y = weight_wave01, 
                        by ="ResponseId")

head(df_wave01$ticket)
data_w01 <- 
  df_wave01 %>% 
  dplyr::select(
    idencuestado=ticket,
    folio_encuestado,
    consentimiento=ci,
    cs_01:cs_15,
    everything()) %>% 
  rename(s4_03_1_0=s4_03_1.0,
         s4_03_2_0=s4_03_2.0,
         s4_03_3_0=s4_03_3.0,
         s4_03_4_0=s4_03_4.0,
         s4_03_5_0=s4_03_5.0,
         s4_03_6_0=s4_03_6.0) %>% 
  # KEEP aquellos que ACEPTAN participar
  filter(consentimiento==1) %>% 
  #identificamos casos
  rownames_to_column(var = "id") %>%
  # eliminamos caso (respuesta vacia) 
  filter(!(id == 272)) %>% 
  select(-id)

data_w01 <- data_w01 %>%
  rename(
    cs_genero = cs_01,
    cs_educ = cs_02,
    cs_edad = cs_03,
    cs_comuna = cs_04,
    fam_solo = cs_05_1,
    fam_amigos = cs_05_2,
    fam_pareja = cs_05_3,
    fam_origen = cs_05_4,
    fam_allega = cs_05_5,
    fam_num = cs_06_1,
    fam_hijos = cs_06_2,
    fam_edad_m = cs_07_2,
    fam_edad_p = cs_07_3,
    nse_acti = cs_08,
    nse_ocu = cs_09,
    nse_income = cs_10,
    nse_libros = cs_11,
    ess_1 = cs_12a,
    ess_2 = cs_12b,
    cs_lgbtiq = cs_13,
    cs_etnia_a = cs_14,
    cs_etnia_text = cs_14_5_TEXT,
    cs_nac = cs_15,
    edm_madre = s2_cg_01_1,
    edm_padre = s2_cg_01_2,
    edm_ambos = s2_cg_01_3,
    edm_herma = s2_cg_01_4,
    edm_abuelo = s2_cg_01_5,
    edm_otro = s2_cg_01_6,
    edm_num = s2_cg_02,
    edm_admi = s2_cg_03,
    edm_tipo = s2_cg_04,
    edm_comuna = s2_cg_05,
    edm_rend_lugar = s2_cg_06_1,
    edm_rend_hist = s2_cg_06_2,
    edm_rend_lectura = s2_cg_06_3,
    edm_rend_tiempo = s2_cg_06_4,
    edm_rend_nota = s2_cg_07,
    edm_histo = s2_cg_08,
    edm_psu = s2_cg_09,
    nse_madre = s2_cs_01_1,
    nse_padre = s2_cs_01_2,
    nse_abuela_m = s2_cs_01_3,
    nse_abuelo_m = s2_cs_01_4,
    nse_abuela_p = s2_cs_01_5,
    nse_abuelo_p = s2_cs_01_6,
    edm_nse_madre = s2_cs_02_1,
    edm_nse_padre = s2_cs_02_2,
    edm_libros = s2_cs_03,
    edm_ess = s2_cs_04,
    ap_disc_desacuerdo = s2_p_e_01_1,
    ap_disc_expresar = s2_p_e_01_2,
    ap_disc_hechos = s2_p_e_01_3,
    ap_disc_op_distinta = s2_p_e_01_4,
    ap_disc_conversar = s2_p_e_01_5,
    ap_disc_dist_puntos = s2_p_e_01_6,
    ap_disc_reflexion = s2_p_e_01_7,
    convi_respeto = s2_p_e_01_8,
    convi_seguro = s2_p_e_01_9,
    convi_llevarse = s2_p_e_01_10,
    soc_taller = s2_p_e_02_1,
    soc_elecciones = s2_p_e_02_2,
    soc_calumno = s2_p_e_02_3,
    soc_foros = s2_p_e_02_4,
    soc_charla = s2_p_e_02_5,
    soc_medioam = s2_p_e_02_6,
    soc_sercom = s2_p_e_02_7,
    soc_focivi = s2_p_e_02_8,
    soc_debate = s2_p_e_02_9,
    form_respeto = s2_p_e_03_1,
    form_valores = s2_p_e_03_2,
    form_imp_voto = s2_p_e_03_3,
    form_exp_voto = s2_p_e_03_4,
    form_part = s2_p_e_03_5,
    form_ley = s2_p_e_03_6,
    form_econo = s2_p_e_03_7,
    ense_formciv = s2_p_e_04,
    part_pol_voto = s2_p_e_05_1,
    part_pol_cand = s2_p_e_05_2,
    part_pol_cealum = s2_p_e_05_3,
    part_pol_marcha_pas = s2_p_e_05_4,
    part_pol_marcha_dis = s2_p_e_05_5,
    part_pol_bloqueo = s2_p_e_05_6,
    part_pol_rayar = s2_p_e_05_7,
    part_pol_toma = s2_p_e_05_8,
    part_pol_volunt = s2_p_e_05_9,
    part_pol_firma = s2_p_e_05_10,
    part_pol_donar = s2_p_e_05_11,
    marcha_amig = s2_p_e_05_12,
    marcha_comp = s2_p_e_05_13,
    marcha_pad = s2_p_e_05_14,
    marcha_fam = s2_p_e_05_15,
    pol_part_edad = s2_p_e_05a,
    pol_part_primer = s2_p_e_05b,
    conv_padr_poli = s2_p_f_01_1,
    conv_amig_poli = s2_p_f_01_2,
    part_pol_info_esc = s2_p_f_01_3,
    part_pol_info_tv = s2_p_f_01_4,
    part_pol_online = s2_p_f_01_5,
    part_online_post = s2_p_f_01_6,
    part_online_com = s2_p_f_01_7,
    part_online_seg = s2_p_f_01_8,
    part_pol_m_voto = s2_p_f_02a_1,
    part_pol_m_macha = s2_p_f_02a_2,
    part_pol_m_donar = s2_p_f_02a_3,
    part_pol_m_opinion = s2_p_f_02a_4,
    part_pol_p_voto = s2_p_f_02b_1,
    part_pol_p_macha = s2_p_f_02b_2,
    part_pol_p_donar = s2_p_f_02b_3,
    part_pol_p_opinion = s2_p_f_02b_4,
    incent_lect = s2_p_f_03_1,
    incent_notas = s2_p_f_03_2,
    incent_univ = s2_p_f_03_3,
    incent_polit = s2_p_f_03_4,
    incent_obed = s2_p_f_03_5,
    int_des_padres_3y4 = s2_p_f_04a_1,
    int_medio_padres_3y4 = s2_p_f_04a_2,
    int_ig_gen_padres_3y4 = s2_p_f_04a_3,
    int_pol_padres_3y4 = s2_p_f_04a_4,
    int_des_3y4 = s2_p_f_04b_1,
    int_medio_3y4 = s2_p_f_04b_2,
    int_ig_gen_3y4 = s2_p_f_04b_3,
    int_pol_3y4 = s2_p_f_04b_4,
    int_des_amigos_3y4 = s2_p_f_04c_1,
    int_medio_amigos_3y4 = s2_p_f_04c_2,
    int_ig_gen_amigos_3y4 = s2_p_f_04c_3,
    int_pol_amigos_3y4 = s2_p_f_04c_4,
    pos_pol_m_3y4 = s2_p_f_05_1,
    pos_pol_p_3y4 = s2_p_f_05_2,
    op_pol_padres_3y4 = s2_p_f_06,
    op_pol_amigos_3y4 = s2_p_f_07,
    part_pol_firma_21 = s3_es_01_1,
    part_pol_marc_pac_21 = s3_es_01_2,
    part_pol_marc_dis_21 = s3_es_01_3,
    part_pol_fem_21 = s3_es_01_4,
    part_pol_cac_21 = s3_es_01_5,
    part_pol_cab_21 = s3_es_01_6,
    part_pol_bloq_21 = s3_es_01_7,
    part_pol_rayar_21 = s3_es_01_8,
    part_pol_toma_21 = s3_es_01_9,
    part_pol_com_21 = s3_es_01_10,
    marcha_amig_21 = s3_es_01_11,
    marcha_comp_21 = s3_es_01_12,
    marcha_pad_21 = s3_es_01_13,
    marcha_fam_21 = s3_es_01_14,
    conv_padres_21 = s3_es_02_1,
    conv_amigos_21 = s3_es_02_2,
    part_pol_info_esc_21 = s3_es_02_3,
    part_pol_info_tv_21 = s3_es_02_4,
    part_pol_online_info_21 = s3_es_02_5,
    part_pol_online_post_21 = s3_es_02_6,
    part_pol_online_com_21 = s3_es_02_7,
    part_pol_online_seg_21 = s3_es_02_8,
    part_pol_firma_20 = s3_pc_01_1,
    part_pol_marc_pac_20 = s3_pc_01_2,
    part_pol_marc_dis_20 = s3_pc_01_3,
    part_pol_fem_20 = s3_pc_01_4,
    part_pol_cac_20 = s3_pc_01_5,
    part_pol_cab_20 = s3_pc_01_6,
    part_pol_bloq_20 = s3_pc_01_7,
    part_pol_rayar_20 = s3_pc_01_8,
    part_pol_toma_20 = s3_pc_01_9,
    part_pol_com_20 = s3_pc_01_10,
    marcha_amig_20 = s3_pc_01_11,
    marcha_comp_20 = s3_pc_01_12,
    marcha_pad_20 = s3_pc_01_13,
    marcha_fam_20 = s3_pc_01_14,
    conv_padres_20 = s3_pc_02_1,
    conv_amigos_20 = s3_pc_02_2,
    part_pol_info_esc_20 = s3_pc_02_3,
    part_pol_info_tv_20 = s3_pc_02_4,
    part_pol_online_info_20 = s3_pc_02_5,
    part_pol_online_post_20 = s3_pc_02_6,
    part_pol_online_com_20 = s3_pc_02_7,
    part_pol_online_seg_20 = s3_pc_02_8,
    voto_pres_17 = s3_pc_03_1,
    voto_pleb = s3_pc_03_2,
    voto_const = s3_pc_03_3,
    voto_fut = s3_pc_04_1,
    int_pol = s4_01,
    pos_pol = s4_02,
    just_marcha = s4_03_1,
    just_bloq = s4_03_2,
    just_toma = s4_03_3,
    just_funa = s4_03_4,
    just_rayar = s4_03_5,
    just_carab = s4_03_6,
    conf_gob = s4_03_1_0,
    conf_trib = s4_03_2_0,
    conf_part = s4_03_3_0,
    conf_cong = s4_03_4_0,
    conf_per = s4_03_5_0,
    conf_conv = s4_03_6_0,
    op_pol_des = s4_04_1,
    op_pol_redis = s4_04_2,
    op_pol_hom = s4_04_3,
    op_pol_abo = s4_04_4,
    op_pol_inm = s4_04_5
  )


# Identificar duplicados
ip1 <- questionr::freq(data_w01$IPAddress,total = TRUE) %>% # Frecuencia de cada IP
  rownames_to_column() %>%                              # ID para IP
  filter(n>=2)                                          # Keep IP >=2

datip01 <- data_w01 %>% 
  filter(IPAddress %in% ip1$rowname, Finished==1) %>% # Filtro ip duplicada y Finished=1
  select(ResponseId,IPAddress,Finished,cs_genero,cs_edad, cs_educ,everything ()) %>% 
  arrange(IPAddress,Finished) # Ordenar la base según IP y Finished para observar patrón 

# Paso II: Duplicados base Finished==1
ip2 <- questionr::freq(x = datip01$IPAddress,total = TRUE) %>%  # Frecuencia de cada IP
        rownames_to_column() %>%                                # ID para IP
        filter(n>=2)                                            # Keep IP >=2

datip03 <- datip01 %>% 
  filter(IPAddress %in% ip2$rowname) %>% # Filtro ip duplicada y Finished=1
  select(ResponseId,IPAddress, cs_genero,cs_edad, cs_educ, StartDate, EndDate) %>% 
  arrange(IPAddress,cs_genero,cs_edad, cs_educ) 

dup1<- length(unique(datip03$IPAddress))
# Paso III: Casos identifos
identical_cases_w01<- datip03 %>% 
  group_by(IPAddress) %>% 
  summarise(sexo=var(cs_genero,na.rm = T),       # calcular varianza grupal  
            edad=var(cs_edad,na.rm = T),
            edcep=var(cs_educ,na.rm = T)) %>% 
  filter(sexo==0 & edad==0 & edcep==0)      # filtrar x varianza 0 (caso identico)

data_w01 %>% 
  filter(IPAddress %in% identical_cases_w01$IPAddress) %>% 
  select(ResponseId,IPAddress,StartDate, EndDate) %>% 
  arrange(IPAddress,StartDate)

# eliminar: 
data_w01 <-
  data_w01 %>%
  filter(!(
    ResponseId %in% c(
      "R_21vxpjb2LRmDn17",
      "R_9Y33wTAg7HBSEAp",
      "R_1Q3pnX4WYL0Okdo"
    )
  ))

# Filtrar por folio encuestado_________________________________________________
df_duplicados <- 
sjmisc::frq(data_w01$folio_encuestado) %>% 
  data.frame() %>% 
  dplyr::filter(frq>=2) %>% 
  dplyr::select(val)

folio_dup <- 
data_w01 %>% 
  dplyr::filter(folio_encuestado %in% df_duplicados$val) %>% 
  dplyr::select(
    ResponseId,
    folio_encuestado,StartDate,EndDate)

folio_dup$start_date <- as.Date(folio_dup$StartDate)

folio_dup_maxdate <- 
folio_dup %>% 
  dplyr::group_by(folio_encuestado) %>% 
  dplyr::slice(which.max(start_date))


# filtrar los Responde ID para los folios duplicados
data_w01a <-
  data_w01 %>%
  dplyr::filter(!(ResponseId %in% folio_dup_maxdate$ResponseId))

# Check final de duplicados
sjmisc::frq(data_w01a$folio_encuestado) %>% 
  data.frame() %>% 
  filter(frq>=2) %>% 
  select(val)

data_w01a %>% 
  dplyr::filter(folio_encuestado %in% 
                  c("8598a08b0db0c7f3","9d625874787491a5")) %>% 
  dplyr::select(
    ResponseId,
    folio_encuestado,StartDate,EndDate) %>% 
  arrange(folio_encuestado)

# eliminar: 
data_w01 <-
  data_w01a %>%
  #eliminamos casos con misma fecha, pero con horarios posteriores
  filter(!(
    ResponseId %in% c(
      "R_1OxdTfxGgO2lEFH",
      "R_2ros4So2NBl4jOw",
      "R_2BssYgRjjTmh2U4"
    )
  ))

dim(data_w01)
data_w01$IPAddress <- NULL
# #rename de variables

# etiquetado
sjlabelled::set_label(data_w01$idencuestado) <- "Identificador encuestado (original)"
sjlabelled::set_label(data_w01$folio_encuestado) <- "Folio encuestado (panel)"
sjlabelled::set_label(data_w01$consentimiento) <- "Consentimiento informado"
sjlabelled::set_label(data_w01$weight_w01) <- "Weights (ebalance) w01"
sjlabelled::set_label(data_w01$weight_na0_w01) <- "Weights recode NA = 0 (ebalance) w01"

sjPlot::view_df(data_w01,
                show.na = T,
                show.frq = T,
                show.prc = T,
                show.type = T,
                file = here::here("output/codebook_w01.html"))

# Guardar datos
save(data_w01,file = here::here("output/data_01.RData"))
haven::write_dta(data = data_w01,path = here::here("output/data_01.dta"))
```

# Ola 2

```{r}
options(scipen=999)
rm(list=ls())
df_wave02 <- haven::read_sav(file = here::here("input/data/original/Ola_2.sav"))
weight_wave02 <- haven::read_dta(file = here::here("input/data/proc/weight_w02.dta"))
names(df_wave02)
head(df_wave02$ticket)
table(df_wave02$ticket==weight_wave02$ticket)
table(df_wave02$ResponseId==weight_wave02$ResponseId)
weight_wave02$ticket <- NULL
#seleccionar ID proveniente de la variable ticket
df_wave02$folio_encuestado<- stringr::str_split(df_wave02$ticket,pattern = "_",simplify = T)[,1]
df_wave02 <- left_join(x = df_wave02,
                        y = weight_wave02,
                        by = "ResponseId")

data_w02 <- 
  df_wave02 %>% 
  dplyr::select(
    idencuestado=ticket,
    folio_encuestado,
    cs_01:cs_15, 
    everything()) 

data_w02 <- data_w02 %>% 
  rename(
    cs_genero = cs_01,
    cs_educ = cs_02,
    cs_edad = cs_03,
    nse_acti = cs_08,
    nse_ocu = cs_09,
    cs_comuna = cs_04,
    fam_solo = cs_05_1,
    fam_amigos = cs_05_2,
    fam_pareja = cs_05_3,
    fam_origen = cs_05_4,
    fam_allega = cs_05_5,
    fam_num = cs_06_1,
    fam_hijos = cs_06_2,
    fam_edad_m = cs_07_1,
    fam_edad_p = cs_07_2,
    nse_income = cs_10,
    nse_libros = cs_11,
    ess_1 = cs_12a,
    ess_2 = cs_12b,
    cs_lgbtiq = cs_13,
    cs_etnia_a = cs_14,
    cs_etnia_text = cs_14_5_TEXT,
    cs_nac = cs_15,
    est_actual = edsup_01,
    est_act_tipo_inst = edsup_02a,
    est_act_tipo_inst_otro = edsup_02a_4_TEXT,
    est_act_nom_inst = edsup_02a_01,
    est_act_carrera = edsup_02a_02,
    est_egre_tipo_inst = edsup_02b,
    est_egre_tipo_inst_otro = edsup_02b_4_TEXT,
    est_egre_nom_inst = edsup_02b_01,
    est_egre_carrera = edsup_02b_02,
    est_act_financia_cred_fs = edsup_03a_1,
    est_act_financia_cred_corfo = edsup_03a_2,
    est_act_financia_cred_cae = edsup_03a_3,
    est_act_financia_gratuidad = edsup_03a_4,
    est_act_financia_becas = edsup_03a_5,
    est_act_financia_propio = edsup_03a_6,
    est_egre_financia_cred_fs = edsup_03b_1,
    est_egre_financia_cred_corfo = edsup_03b_2,
    est_egre_financia_cred_cae = edsup_03b_3,
    est_egre_financia_gratuidad = edsup_03b_4,
    est_egre_financia_becas = edsup_03b_5,
    est_egre_financia_propio = edsup_03b_6,
    est_act_ap_disc_desacuerdo = edsup_04a_1,
    est_act_ap_disc_expresar = edsup_04a_2,
    est_act_ap_disc_hechos = edsup_04a_3,
    est_act_ap_disc_op_distinta = edsup_04a_4,
    est_act_ap_disc_conversar = edsup_04a_5,
    est_act_ap_disc_dist_puntos = edsup_04a_6,
    est_act_ap_disc_reflexion = edsup_04a_7,
    est_egre_ap_disc_desacuerdo = edsup_04b_1,
    est_egre_ap_disc_expresar = edsup_04b_2,
    est_egre_ap_disc_hechos = edsup_04b_3,
    est_egre_ap_disc_op_distinta = edsup_04b_4,
    est_egre_ap_disc_conversar = edsup_04b_5,
    est_egre_ap_disc_dist_puntos = edsup_04b_6,
    est_egre_ap_disc_reflexion = edsup_04b_7,
    est_act_form_respeto = edsup_05a_1,
    est_act_form_valores = edsup_05a_2,
    est_act_form_imp_voto = edsup_05a_3,
    est_act_form_exp_voto = edsup_05a_4,
    est_act_form_part = edsup_05a_5,
    est_act_form_ley = edsup_05a_6,
    est_act_form_econo = edsup_05a_7,
    est_egre_form_respeto = edsup_05b_1,
    est_egre_form_valores = edsup_05b_2,
    est_egre_form_imp_voto = edsup_05b_3,
    est_egre_form_exp_voto = edsup_05b_4,
    est_egre_form_part = edsup_05b_5,
    est_egre_form_ley = edsup_05b_6,
    est_egre_form_econo = edsup_05b_7,
    est_act_activ_taller = edsup_06a_1,
    est_act_activ_eleccion = edsup_06a_2,
    est_act_activ_campaña = edsup_06a_3,
    est_act_activ_foro = edsup_06a_4,
    est_act_activ_charla = edsup_06a_5,
    est_act_activ_medio = edsup_06a_6,
    est_act_activ_comunitaria = edsup_06a_7,
    est_act_activ_form_civ = edsup_06a_8,
    est_act_activ_debate = edsup_06a_9,
    est_egre_activ_taller = edsup_06b_1,
    est_egre_activ_eleccion = edsup_06b_2,
    est_egre_activ_campaña = edsup_06b_3,
    est_egre_activ_foro = edsup_06b_4,
    est_egre_activ_charla = edsup_06b_5,
    est_egre_activ_medio = edsup_06b_6,
    est_egre_activ_comunitaria = edsup_06b_7,
    est_egre_activ_form_civ = edsup_06b_8,
    est_egre_activ_debate = edsup_06b_9,
    est_act_rend_lugar = edsup_07a_1,
    est_act_rend_lectura = edsup_07a_2,
    est_act_rend_tiempo = edsup_07a_3,
    est_act_rend_nota = edsup_08a,
    est_egre_rend_lugar = edsup_07b_1,
    est_egre_rend_lectura = edsup_07b_2,
    est_egre_rend_tiempo = edsup_07b_3,
    est_egre_rend_nota = edsup_08b,
    est_egre_part_pol_firma = edsup_09_1,
    est_egre_part_pol_marc_pac = edsup_09_2,
    est_egre_part_pol_marc_dis = edsup_09_3,
    est_egre_part_pol_fem = edsup_09_4,
    est_egre_part_pol_cac = edsup_09_5,
    est_egre_part_pol_cab = edsup_09_6,
    est_egre_part_pol_cam = edsup_09_7,
    est_egre_part_pol_bloq = edsup_09_8,
    est_egre_part_pol_rayar = edsup_09_9,
    est_egre_part_pol_toma = edsup_09_10,
    est_egre_part_pol_com = edsup_09_11,
    est_egre_marcha_amig = edsup_09_12,
    est_egre_marcha_comp = edsup_09_13,
    est_egre_marcha_pad = edsup_09_14,
    est_egre_marcha_fam = edsup_09_15,
    est_egre_conv_padres = edsup_10_1,
    est_egre_conv_amigos = edsup_10_2,
    est_egre_part_pol_info_esc = edsup_10_3,
    est_egre_part_pol_info_tv = edsup_10_4,
    est_egre_part_pol_online_info = edsup_10_5,
    est_egre_part_pol_online_post = edsup_10_6,
    est_egre_part_pol_online_com = edsup_10_7,
    est_egre_part_pol_online_seg = edsup_10_8,
    part_pol_firma = part_act_01_1,
    part_pol_marc_pac = part_act_01_2,
    part_pol_marc_dis = part_act_01_3,
    part_pol_fem = part_act_01_4,
    part_pol_cac = part_act_01_5,
    part_pol_cab = part_act_01_6,
    part_pol_cam = part_act_01_7,
    part_pol_bloq = part_act_01_8,
    part_pol_rayar = part_act_01_9,
    part_pol_toma = part_act_01_10,
    part_pol_com = part_act_01_11,
    marcha_amig = part_act_01_12,
    marcha_comp = part_act_01_13,
    marcha_pad = part_act_01_14,
    marcha_fam = part_act_01_15,
    conv_padres = part_act_02_1,
    conv_amigos = part_act_02_2,
    part_pol_info_esc = part_act_02_3,
    part_pol_info_tv = part_act_02_4,
    part_pol_online_info = part_act_02_5,
    part_pol_online_post = part_act_02_6,
    part_pol_online_com = part_act_02_7,
    part_pol_online_seg = part_act_02_8,
    voto_conv2 = part_act_03_1,
    voto_muni = part_act_03_2,
    voto_gob = part_act_03_4,
    voto_fut = s3_pc_04_1,
    int_des = act_01_1,
    int_medio = act_01_2,
    int_ig_gen = act_01_3,
    int_pol = act_01_4,
    op_pol = act_02,
    auto_efic_saber = act_03_1,
    auto_efic_decir = act_03_2,
    auto_efic_entender = act_03_3,
    auto_efic_escucha = act_03_4,
    auto_efic_comprende = act_03_5,
    pos_pol = s4_02,
    satis_dem = act_04,
    ig_etn_educ = act_05_1,
    ig_etn_trab = act_05_2,
    ig_etn_respeto = act_05_3,
    ig_etn_cargos = act_05_4,
    ig_etn_derechos = act_05_5,
    ig_gen_gob = act_06_1,
    ig_gen_hijos = act_06_2,
    ig_gen_pol = act_06_3,
    ig_gen_trab = act_06_4,
    ig_gen_salario = act_06_5,
    ig_gen_lider = act_06_6,
    ig_gen_derechos = act_06_7,
    ig_gen_hogar = act_06_8,
    ig_gen_decisiones = act_06_9,
    ig_inm_educ = act_07_1,
    ig_inm_cost = act_07_2,
    ig_inm_derechos = act_07_3,
    ig_inm_insuf_trab = act_07_4,
    ig_inm_ocupan_trab = act_07_5,
    ig_inm_no_ajustan = act_07_6,
    autorit_poder = act_08_1,
    autorit_just_orden = act_08_2,
    autorit_just_econo = act_08_3,
    autorit_gob_fuerte = act_08_4,
    autorit_mand_fuerte = act_08_5,
    autorit_obediencia = act_08_6,
    just_marcha = s4_03_1,
    just_bloq = s4_03_2,
    just_toma = s4_03_3,
    just_funa = s4_03_4,
    just_rayar = s4_03_5,
    just_carab = s4_03_6,
    conf_gob = act_09_1,
    conf_trib = act_09_2,
    conf_part = act_09_3,
    conf_cong = act_09_4,
    conf_mmc = act_09_5,
    conf_per = act_09_6,
    conf_conv = act_09_7,
    corrup_gob = act_10_1,
    corrup_trib = act_10_2,
    corrup_part = act_10_3,
    corrup_cong = act_10_4,
    corrup_mmc = act_10_5,
    corrup_conv = act_10_7,
    buen_ciud_voto = act_11_1,
    buen_ciud_autoridades = act_11_2,
    buen_ciud_marc_pac = act_11_3,
    buen_ciud_comun = act_11_4,
    buen_ciud_ddhh = act_11_5,
    buen_ciud_impuesto = act_11_6,
    buen_ciud_ley = act_11_7,
    op_pol_des = act_12_1,
    op_pol_redis = act_12_2,
    op_pol_merit = act_12_3,
    op_pol_esfuerzo = act_12_4,
    op_pol_des_edu = act_12_5,
    op_pol_des_salud = act_12_6,
    op_pol_hom = act_12_7,
    op_pol_abo = act_12_8,
    op_pol_inm = act_12_9
  )

# DUPLICADOS: Ola 2.............................................................
ip1 <- questionr::freq(data_w02$IPAddress,total = TRUE) %>% # Frecuencia de cada IP
  rownames_to_column() %>%                              # ID para IP
  filter(n>=2)                                          # Keep IP >=2

datip01 <- data_w02 %>% 
  filter(IPAddress %in% ip1$rowname, Finished==1) %>% # Filtro ip duplicada y Finished=1
  select(ResponseId,IPAddress,Finished,cs_genero,cs_edad, cs_educ,everything ()) %>% 
  arrange(IPAddress,Finished) # Ordenar la base según IP y Finished para observar patrón 

# Paso II: Duplicados base Finished==1
ip2 <- questionr::freq(x = datip01$IPAddress,total = TRUE) %>%  # Frecuencia de cada IP
        rownames_to_column() %>%                                # ID para IP
        filter(n>=2)                                            # Keep IP >=2

datip03 <- datip01 %>% 
  filter(IPAddress %in% ip2$rowname) %>% # Filtro ip duplicada y Finished=1
  select(ResponseId,IPAddress, cs_genero,cs_edad, cs_educ, StartDate, EndDate) %>% 
  arrange(IPAddress,cs_genero,cs_edad, cs_educ) 

dup1<- length(unique(datip03$IPAddress))
# Paso III: Casos identifos
identical_cases_w02<- datip03 %>% 
  group_by(IPAddress) %>% 
  summarise(sexo=var(cs_genero,na.rm = T),       # calcular varianza grupal  
            edad=var(cs_edad,na.rm = T),
            edcep=var(cs_educ,na.rm = T)) %>% 
  filter(sexo==0 & edad==0 & edcep==0)      # filtrar x varianza 0 (caso identico)


data_w02 %>% 
  filter(IPAddress %in% identical_cases_w02$IPAddress) %>% 
  select(ResponseId,IPAddress,StartDate, EndDate) %>% 
  arrange(IPAddress,StartDate)

# eliminar: 
data_w02 <-
  data_w02 %>%
  filter(!(
    ResponseId %in% c(
      "R_2AFF3L5fP9gWJmB",
      "R_cObKssORAA8hRDP"
    )
  ))

# Filtrar por folio encuestado_________________________________________________
folio_duplicado <- 
sjmisc::frq(data_w02$folio_encuestado) %>% 
  data.frame() %>% 
  filter(frq>=2) %>% 
  select(val)


folio_dup <- 
data_w02 %>% 
  filter(folio_encuestado %in% folio_duplicado$val) %>% 
  select(
    ResponseId,
    folio_encuestado,StartDate)

folio_dup_maxdate <- 
folio_dup %>% 
  group_by(folio_encuestado) %>% 
  slice(which.max(StartDate))
# filtrar los Responde ID para los folios duplicados
data_w02a <-
  data_w02 %>%
  filter(!(
    ResponseId %in% folio_dup_maxdate$ResponseId
  ))

# Check final de duplicados
sjmisc::frq(data_w02a$folio_encuestado) %>% 
  data.frame() %>% 
  filter(frq>=2) %>% 
  select(val)

#duplicado "808a03736079c53c"
data_w02a %>% 
  dplyr::filter(folio_encuestado %in% 
                  c("808a03736079c53c")) %>% 
  dplyr::select(
    ResponseId,
    folio_encuestado,StartDate,EndDate) %>% 
  arrange(folio_encuestado)

# eliminar: 
data_w02 <-
  data_w02a %>%
  #eliminamos casos con misma fecha, pero con horarios posteriores
  filter(!(ResponseId %in% c("R_zcXU8ezyqO2aDrX")
  ))

dim(data_w02)
data_w02$IPAddress <- NULL
# etiquetado
sjlabelled::set_label(data_w02$idencuestado) <- "Identificador encuestado (original)"
sjlabelled::set_label(data_w02$folio_encuestado) <- "Folio encuestado (panel)"
sjlabelled::set_label(data_w02$weight_w02) <- "Weights (ebalance) w02"
sjlabelled::set_label(data_w02$weight_na0_w02) <- "Weights recode NA = 0 (ebalance) w02"


sjPlot::view_df(data_w02,
                show.na = T,
                show.frq = T,
                show.prc = T,
                show.type = T,
                file = here::here("output/codebook_w02.html"))
# Guardar datos
save(data_w02,file = here::here("output/data_02.RData"))
haven::write_dta(data = data_w02,path = here::here("output/data_02.dta"))
```

# Ola 3

```{r}
options(scipen=999)
rm(list=ls())
df_wave03 <- haven::read_sav(file = here::here("input/data/original/Ola_3.sav"))
weight_wave03 <- haven::read_dta(file = here::here("input/data/proc/weight_w03.dta"))
names(df_wave03)
head(df_wave03$ticket)
weight_wave03$ticket <- NULL
#seleccionar ID proveniente de la variable ticket
df_wave03$folio_encuestado<- stringr::str_split(df_wave03$ticket,pattern = "_",simplify = T)[,1]
df_wave03 <- left_join(x = df_wave03,y = weight_wave03, by ="ResponseId")

data_w03 <- 
  df_wave03 %>% 
  dplyr::select(
    idencuestado=ticket,
    folio_encuestado,
    cs_01:cs_15, 
    everything())

data_w03 <- data_w03 %>% 
  rename(
    cs_genero = cs_01,
    cs_educ = cs_02,
    cs_edad = cs_03,
    nse_acti = cs_08,
    nse_ocu = cs_09,
    cs_comuna = cs_04,
    fam_solo = cs_05_1,
    fam_amigos = cs_05_2,
    fam_pareja = cs_05_3,
    fam_origen = cs_05_4,
    fam_allega = cs_05_5,
    fam_num = cs_06_1,
    fam_hijos = cs_06_2,
    fam_edad_m = cs_07_1,
    fam_edad_p = cs_07_2,
    nse_income = cs_10,
    nse_libros = cs_11,
    ess_1 = cs_12a,
    ess_2 = cs_12b,
    cs_lgtbiq = cs_13,
    cs_etnia_a = cs_14,
    cs_etnia_text = cs_14_5_TEXT,
    cs_nac = cs_15,
    esup_status = edsup_01,
    esup_tipo = edsup_02a,
    esup_tipo_text = edsup_02a_4_TEXT,
    esup_nombre = edsup_02a_01,
    esup_carrera = edsup_02a_02,
    esup_year = edsup_02a_03,
    esup_fin_fsol = edsup_03a_1,
    esup_fin_corfo = edsup_03a_2,
    esup_fin_cae = edsup_03a_3,
    esup_fin_grat = edsup_03a_4,
    esup_fin_beca = edsup_03a_5,
    esup_fin_auto = edsup_03a_6,
    aper_desacuerdo = edsup_04a_1,
    aper_opinion = edsup_04a_2,
    aper_actualidad = edsup_04a_3,
    aper_opdistinto = edsup_04a_4,
    aper_conversar = edsup_04a_5,
    aper_puntos = edsup_04a_6,
    aper_reflexion = edsup_04a_7,
    ense_respeto = edsup_05a_1,
    ense_democ = edsup_05a_2,
    ense_voto = edsup_05a_3,
    ense_elec = edsup_05a_4,
    ense_movi = edsup_05a_5,
    ense_resley = edsup_05a_6,
    ense_econ = edsup_05a_7,
    soc_taller = edsup_06a_1,
    soc_elecciones = edsup_06a_2,
    soc_calumno = edsup_06a_3,
    soc_foros = edsup_06a_4,
    soc_charla = edsup_06a_5,
    soc_medioam = edsup_06a_6,
    soc_sercom = edsup_06a_7,
    soc_forcivi = edsup_06a_8,
    soc_debate = edsup_06a_9,
    esup_ren_gen = edsup_07a_1,
    esup_hab_lect = edsup_07a_2,
    esup_tiem_est = edsup_07a_3,
    esup_rend_21 = edsup_08a,
    part_pol_firma_21b = part_act_01_1,
    part_pol_marc_pac_21b = part_act_01_2,
    part_pol_marc_dis_21b = part_act_01_3,
    part_pol_fem_21b = part_act_01_4,
    part_pol_cac_21b = part_act_01_5,
    part_pol_cab_21b = part_act_01_6,
    part_pol_camp_21b = part_act_01_7,
    part_pol_bloq_21b = part_act_01_8,
    part_pol_rayar_21b = part_act_01_9,
    part_pol_toma_21b = part_act_01_10,
    part_pol_com_21b = part_act_01_11,
    marcha_amig_21b = part_act_01_12,
    marcha_comp_21b = part_act_01_13,
    marcha_pad_21b = part_act_01_14,
    marcha_fam_21b = part_act_01_15,
    conv_padres_21b = part_act_02_1,
    conv_amigos_21b = part_act_02_2,
    part_pol_info_esc_21b = part_act_02_3,
    part_pol_info_tv_21b = part_act_02_4,
    part_pol_online_info_21b = part_act_02_5,
    part_pol_online_post_21b = part_act_02_6,
    part_pol_online_com_21b = part_act_02_7,
    part_pol_online_seg_21b = part_act_02_8,
    voto_dipu = part_act_03_1,
    voto_privuelta = part_act_03_2,
    voto_segvuelta = part_act_03_4,
    int_des = act_01_1,
    int_medio = act_01_2,
    int_ig_gen = act_01_3,
    int_pol = act_01_4,
    op_pol = act_02,
    auto_efic_saber = act_03_1,
    auto_efic_decir = act_03_2,
    auto_efic_entender = act_03_3,
    auto_efic_escucha = act_03_4,
    auto_efic_comprende = act_03_5,
    pos_pol = s4_02,
    satis_dem = act_04,
    ig_etn_educ = act_05_1,
    ig_etn_trab = act_05_2,
    ig_etn_respeto = act_05_3,
    ig_etn_cargos = act_05_4,
    ig_etn_derechos = act_05_5,
    ig_gen_gob = act_06_1,
    ig_gen_hijos = act_06_2,
    ig_gen_pol = act_06_3,
    ig_gen_trab = act_06_4,
    ig_gen_salario = act_06_5,
    ig_gen_lider = act_06_6,
    ig_gen_derechos = act_06_7,
    ig_gen_hogar = act_06_8,
    ig_gen_decisiones = act_06_9,
    ig_inm_educ = act_07_1,
    ig_inm_cost = act_07_2,
    ig_inm_derechos = act_07_3,
    ig_inm_insuf_trab = act_07_4,
    ig_inm_ocupan_trab = act_07_5,
    ig_inm_no_ajustan = act_07_6,
    autorit_poder = act_08_1,
    autorit_just_orden = act_08_2,
    autorit_just_econo = act_08_3,
    autorit_gob_fuerte = act_08_4,
    autorit_mand_fuerte = act_08_5,
    autorit_obediencia = act_08_6,
    just_marcha = s4_03_1,
    just_bloq = s4_03_2,
    just_toma = s4_03_3,
    just_funa = s4_03_4,
    just_rayar = s4_03_5,
    just_carab = s4_03_6,
    conf_gob = act_09_1,
    conf_trib = act_09_2,
    conf_part = act_09_3,
    conf_cong = act_09_4,
    conf_mmc = act_09_5,
    conf_per = act_09_6,
    conf_conv = act_09_7,
    corrup_gob = act_10_1,
    corrup_trib = act_10_2,
    corrup_part = act_10_3,
    corrup_cong = act_10_4,
    corrup_mmc = act_10_5,
    corrup_conv = act_10_7,
    buen_ciud_voto = act_11_1,
    buen_ciud_autoridades = act_11_2,
    buen_ciud_marc_pac = act_11_3,
    buen_ciud_comun = act_11_4,
    buen_ciud_ddhh = act_11_5,
    buen_ciud_impuesto = act_11_6,
    buen_ciud_ley = act_11_7,
    op_pol_des = act_12_1,
    op_pol_redis = act_12_2,
    op_pol_merit = act_12_3,
    op_pol_esfuerzo = act_12_4,
    op_pol_des_edu = act_12_5,
    op_pol_des_salud = act_12_6,
    op_pol_hom = act_12_7,
    op_pol_abo = act_12_8,
    op_pol_inm = act_12_9
  )

ip1 <- questionr::freq(data_w03$IPAddress,total = TRUE) %>% # Frecuencia de cada IP
  rownames_to_column() %>%                              # ID para IP
  filter(n>=2)                                          # Keep IP >=2

datip01 <- data_w03 %>% 
  filter(IPAddress %in% ip1$rowname, Finished==1) %>% # Filtro ip duplicada y Finished=1
  select(ResponseId,IPAddress,Finished,cs_genero,cs_edad, cs_educ,everything ()) %>% 
  arrange(IPAddress,Finished) # Ordenar la base según IP y Finished para observar patrón 

# Paso II: Duplicados base Finished==1
ip2 <- questionr::freq(x = datip01$IPAddress,total = TRUE) %>%  # Frecuencia de cada IP
        rownames_to_column() %>%                                # ID para IP
        filter(n>=2)                                            # Keep IP >=2

datip03 <- datip01 %>% 
  filter(IPAddress %in% ip2$rowname) %>% # Filtro ip duplicada y Finished=1
  select(ResponseId,IPAddress, cs_genero,cs_edad, cs_educ, StartDate, EndDate) %>% 
  arrange(IPAddress,cs_genero,cs_edad, cs_educ) 

dup1<- length(unique(datip03$IPAddress))
# Paso III: Casos identifos
identical_cases_w03<- datip03 %>% 
  group_by(IPAddress) %>% 
  summarise(sexo=var(cs_genero,na.rm = T),       # calcular varianza grupal  
            edad=var(cs_edad,na.rm = T),
            edcep=var(cs_educ,na.rm = T)) %>% 
  filter(sexo==0 & edad==0 & edcep==0)      # filtrar x varianza 0 (caso identico)


data_w03 %>% 
  filter(IPAddress %in% identical_cases_w03$IPAddress) %>% 
  select(ResponseId,IPAddress,StartDate, EndDate) %>% 
  arrange(IPAddress,StartDate)

# eliminar: 
data_w03 <-
  data_w03 %>%
  filter(!(
    ResponseId %in% c(
      "R_2PcFkpEtnxphM80",
      "R_1FQSqTv761ucvvD",
      "R_10pVfDYK6vgRPP4"
    )
  ))

# Filtrar por folio encuestado_________________________________________________
folio_duplicado <- 
sjmisc::frq(data_w03$folio_encuestado) %>% 
  data.frame() %>% 
  filter(frq>=2) %>% 
  select(val)

folio_dup <- 
data_w03 %>% 
  filter(folio_encuestado %in% folio_duplicado$val) %>% 
  select(
    ResponseId,
    folio_encuestado,StartDate)

folio_dup_maxdate <- 
folio_dup %>% 
  group_by(folio_encuestado) %>% 
  slice(which.max(StartDate))
# filtrar los Responde ID para los folios duplicados
data_w03a <-
  data_w03 %>%
  filter(!(
    ResponseId %in% folio_dup_maxdate$ResponseId
  ))

# Check final de duplicados
sjmisc::frq(data_w03a$folio_encuestado) %>% 
  data.frame() %>% 
  filter(frq>=2) %>% 
  select(val)

#duplicado "16c6442437d5ff40"
data_w03a %>% 
  dplyr::filter(folio_encuestado %in% 
                  c("16c6442437d5ff40")) %>% 
  dplyr::select(
    ResponseId,
    folio_encuestado,StartDate,EndDate) %>% 
  arrange(folio_encuestado)

# eliminar: 
data_w03 <-
  data_w03a %>%
  #eliminamos casos con misma fecha, pero con horarios posteriores
  filter(!(ResponseId %in% c("R_ekEbQ7JEuOdYW1r")
  ))

dim(data_w03)

data_w03$IPAddress <- NULL
# etiquetado
sjlabelled::set_label(data_w03$idencuestado) <- "Identificador encuestado (original)"
sjlabelled::set_label(data_w03$folio_encuestado) <- "Folio encuestado (panel)"
sjlabelled::set_label(data_w03$weight_w03) <- "Weights (ebalance) w03"
sjlabelled::set_label(data_w03$weight_na0_w03) <- "Weights recode NA = 0 (ebalance) w03"

sjPlot::view_df(data_w03,
                show.na = T,
                show.frq = T,
                show.prc = T,
                show.type = T,
                file = here::here("output/codebook_w03.html")
                )

# Guardar datos
save(data_w03,file = here::here("output/data_03.RData"))
haven::write_dta(data = data_w03,path = here::here("output/data_03.dta"))
```


```{r}
options(scipen=999)
rm(list=ls())
load(here::here("output/data_01.RData"))
load(here::here("output/data_02.RData"))
load(here::here("output/data_03.RData"))

library(dplyr)

#Incluir sufijo de ola en nombres de variables
data_w01b <- data_w01 %>% dplyr::rename_all(funs(paste0(.,"_w01"))) %>% 
  rename(idencuestado = idencuestado_w01,
         folio_encuestado = folio_encuestado_w01)
set_label(data_w01b) <- paste0(get_label(data_w01b)," (w01) ") 

data_w02b <- data_w02 %>% dplyr::rename_all(funs(paste0(.,"_w02"))) %>% 
    rename(folio_encuestado = folio_encuestado_w02) %>% 
    select(-idencuestado_w02)

set_label(data_w02b) <- paste0(get_label(data_w02b)," (w02) ") 

data_w03b <- data_w03 %>% dplyr::rename_all(funs(paste0(.,"_w03"))) %>% 
    rename(folio_encuestado = folio_encuestado_w03) %>%  
    select(-idencuestado_w03)

set_label(data_w03b) <- paste0(get_label(data_w02b)," (w03) ") 


data_wide <- 
  left_join(data_w01b,
            data_w02b, by = "folio_encuestado") %>%
  left_join(data_w03b, by = "folio_encuestado") %>% 
  filter(folio_encuestado %in% data_w01b$folio_encuestado)

# hay duplicados en la base wide?
sjmisc::frq(data_wide$folio_encuestado) %>%
  data.frame() %>% 
  filter(frq>=2) 

data_wide <- data_wide %>% 
  select(-c(RecipientLastName_w03,	
            RecipientFirstName_w03,
            RecipientEmail_w03,
            ExternalReference_w03,
            LocationLatitude_w03,
            LocationLongitude_w03,
            DistributionChannel_w03,	
            UserLanguage_w03,
            
            RecipientLastName_w02,	
            RecipientFirstName_w02,
            RecipientEmail_w02,
            ExternalReference_w02,
            LocationLatitude_w02,
            LocationLongitude_w02,
            DistributionChannel_w02,	
            UserLanguage_w02,
            
            RecipientLastName_w01,	
            RecipientFirstName_w01,
            RecipientEmail_w01,
            ExternalReference_w01,
            LocationLatitude_w01,
            LocationLongitude_w01,
            DistributionChannel_w01,	
            UserLanguage_w01
            ))

sjPlot::view_df(data_wide,
                show.na = T,
                show.frq = T,
                show.prc = T,
                show.type = T,
                file = here::here("output/codebook_wide.html")
                )

# Guardar datos
save(data_wide,file = here::here("output/data_wide.RData"))
```


```{r eval=FALSE, include=FALSE}
# library("qpcR")      
# df01 <- data_w01 %>% 
#   dplyr::select(cs_01:cs_15) %>% 
#   dplyr::select(starts_with("cs_"),everything())
# 
# 
# df_1 <- data.frame("names_w1"=names(df01),
#                    "label_w1"= sjlabelled::get_label(df01))
# 
# df02 <- data_w02 %>% 
#   dplyr::select(cs_01:cs_15) %>% 
#   dplyr::select(starts_with("cs_"),
#                 everything())
# 
# df_2 <- data.frame("names_w2"=names(df02),
#                    "label_w2"=sjlabelled::get_label(df02))
# 
# df03 <- data_w03 %>% 
#   dplyr::select(cs_01:cs_15) 
#   
# df03 <- df03 %>% dplyr::select(starts_with("cs_"),everything())
# 
# df_3 <- data.frame("names_w3"=names(df03),
#                    "label_w3"=sjlabelled::get_label(df03))
# 
# 
# df_1 %>% 
#   xlsx::write.xlsx(file = here::here("output/var_names.xlsx"),append = T,sheetName = "df1",
#                    row.names = F)
# df_2 %>% 
#   xlsx::write.xlsx(file = here::here("output/var_names.xlsx"),append = T,sheetName = "df2",row.names = F)
# df_3 %>% 
#   xlsx::write.xlsx(file = here::here("output/var_names.xlsx"),append = T,sheetName = "df3",row.names = F)

```

