---
title: "Data preparation"
author: "Julio Iturra"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output:
  bookdown::html_document2:
    number_sections: true
    toc: true
    toc_float:
        collapsed: false
    toc_depth: 2
    code_folding: "hide"
editor_options:
  chunk_output_type: console
---

# Setup

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE, 
                      cache = FALSE,
                      results = "hold")
options(scipen=999)
rm(list=ls())
options(knitr.kable.NA = '')
# .rs.restartR()
```

```{css, echo=FALSE}
# /* expandir el espacio del documento*/
body .main-container {
      max-width: 1600px !important;
      width: 1600px !important;
    }
#/* expandir width de la TOC*/
div.tocify {
    width: 22% !important;
    max-width: 331px !important;
    max-height: 102% !important;
}
```

**load packages**
```{r}
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,       # Manipulacion de datos 
               haven,       # importar datos en .dta o .sav
               sjmisc,      # descriptivos y frecuencias
               sjPlot,      # tablas, plots y descriptivos
               sjlabelled,
               summarytools,# resumen de dataframe
               knitr,       # tablas kable
               kableExtra,  # tablas kable personalizadas
               ggplot2,     # plots
               corrplot,    # plot correlacion
               survey
               )

```

# Datos

```{r}
df_wave01 <- haven::read_sav(file = here::here("input/data/original/Ola_1.sav"))
df_wave02 <- haven::read_sav(file = here::here("input/data/original/Ola_2.sav"))
df_wave03 <- haven::read_sav(file = here::here("input/data/original/Ola_3.sav"))

#ponderadores w01
weight_wave01 <- haven::read_dta(file = here::here("input/data/proc/weight_w01.dta"))
```


# Ola 1

```{r}
# names(df_wave01)

#seleccionar ID proveniente de la variable ticket
df_wave01$folio_encuestado<- stringr::str_split(df_wave01$ticket,pattern = "_",simplify = T)[,1]
df_wave01 <- left_join(x = df_wave01,y = weight_wave01, by ="ticket")


head(df_wave01$ticket)
data_w01 <- 
  df_wave01 %>% 
  select(
    idencuestado=ticket,
    folio_encuestado,
    consentimiento=ci,
    cs_01:cs_15, 
    everything()) %>% 
  rename(s4_03_1_0=s4_03_1.0,
         s4_03_2_0=s4_03_2.0,
         s4_03_3_0=s4_03_3.0,
         s4_03_4_0=s4_03_4.0,
         s4_03_5_0=s4_03_5.0,
         s4_03_6_0=s4_03_6.0)

# etiquetado
sjlabelled::set_label(data_w01$idencuestado) <- "Identificador encuestado (original)"
sjlabelled::set_label(data_w01$folio_encuestado) <- "Folio encuestado (panel)"
sjlabelled::set_label(data_w01$consentimiento) <- "Consentimiento informado"

sjPlot::view_df(data_w01, 
                show.na = T,
                show.frq = T, 
                show.prc = T,
                file = here::here("output/codebook_w01.html"))

# Guardar datos
save(data_w01,file = here::here("output/data_01.RData"))
haven::write_dta(data = data_w01,path = here::here("output/data_01.dta"))
```


# Ola 2

```{r}
names(df_wave02)
head(df_wave02$ticket)

#seleccionar ID proveniente de la variable ticket
df_wave02$folio_encuestado<- stringr::str_split(df_wave02$ticket,pattern = "_",simplify = T)[,1]

data_w02 <- 
  df_wave02 %>% 
  select(
    idencuestado=ticket,
    folio_encuestado,
    cs_01:cs_15, 
    everything())

# etiquetado
sjlabelled::set_label(data_w02$idencuestado) <- "Identificador encuestado (original)"
sjlabelled::set_label(data_w02$folio_encuestado) <- "Folio encuestado (panel)"

sjPlot::view_df(data_w02, 
                show.na = T,
                show.frq = T, 
                show.prc = T,
                file = here::here("output/codebook_w02.html"))
# Guardar datos
save(data_w02,file = here::here("output/data_02.RData"))
haven::write_dta(data = data_w02,path = here::here("output/data_02.dta"))
```

# Ola 3

```{r}
names(df_wave03)
head(df_wave03$ticket)

#seleccionar ID proveniente de la variable ticket
df_wave03$folio_encuestado<- stringr::str_split(df_wave03$ticket,pattern = "_",simplify = T)[,1]

data_w03 <- 
  df_wave03 %>% 
  select(
    idencuestado=ticket,
    folio_encuestado,
    cs_01:cs_15, 
    everything())

# etiquetado
sjlabelled::set_label(data_w03$idencuestado) <- "Identificador encuestado (original)"
sjlabelled::set_label(data_w03$folio_encuestado) <- "Folio encuestado (panel)"

sjPlot::view_df(data_w03, 
                show.na = T,
                show.frq = T, 
                show.prc = T,
                file = here::here("output/codebook_w03.html"))

# Guardar datos
save(data_w03,file = here::here("output/data_03.RData"))
haven::write_dta(data = data_w03,path = here::here("output/data_03.dta"))
```
