---
title: "Ponderadores"
author: "Julio Iturra"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output:
  bookdown::html_document2:
    number_sections: true
    toc: true
    toc_float:
        collapsed: false
    toc_depth: 2
    code_folding: "hide"
editor_options:
  chunk_output_type: console
---


# Setup

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE, 
                      cache = FALSE,
                      results = "hold")
options(scipen=999)
rm(list=ls())
options(knitr.kable.NA = '')
```

```{css, echo=FALSE}
# /* expandir el espacio del documento*/
body .main-container {
      max-width: 1600px !important;
      width: 1600px !important;
    }
#/* expandir width de la TOC*/
div.tocify {
    width: 22% !important;
    max-width: 331px !important;
    max-height: 102% !important;
}
```

**load packages**
```{r}
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,       # Manipulacion de datos 
               haven,       # importar datos en .dta o .sav
               sjmisc,      # descriptivos y frecuencias
               sjPlot,      # tablas, plots y descriptivos
               sjlabelled,
               summarytools,# resumen de dataframe
               knitr,       # tablas kable
               kableExtra,  # tablas kable personalizadas
               ggplot2,     # plots
               corrplot,    # plot correlacion
               survey
               )
```


# Datos

```{r}
load(url("https://github.com/jciturras/data-chile/blob/main/data/censo-2017/censo-2017.RData?raw=true"))
save(censo2017,file = "input/data/original/censo2017.RData")

df_wave01 <- haven::read_sav(file = "input/data/original/Ola_1.sav")
df_wave02 <- haven::read_sav(file = "input/data/original/Ola_2.sav")

```

# Preparación

```{r}
df_weights <- 
  df_wave01 %>% 
  filter(ci==1)
```

```{r}
view_df(df_weights,show.prc = T,show.na = T,show.frq = T)
```


```{r}
small.svy.unweighted <- svydesign(ids=~1, data=df_weights)
## Warning: No weights or probabilities supplied, assuming equal probability
```

```{r}
sexo.dist <- data.frame(sexo = c(1, 2),
                        Freq = nrow(df_weights) * c(0.4963, 0.5037))

edad.dist <- data.frame(edad = c(18,19,20,21,22,23,24,25,26,27,28,29,30),
                        Freq = nrow(df_weights) * c(0.0732,0.0680,0.0741,0.0794,
                                                    0.0801,0.0801,0.0827,0.0774,
                                                    0.0760,0.0821,0.0797,0.0689,
                                                    0.0783))
```

```{r}
small.svy.rake <- rake(design = small.svy.unweighted,
                       sample.margins = list(~sexo, ~edad),
                       population.margins = list(sexo.dist, edad.dist))
```

```{r}
summary(weights(small.svy.rake))

small.svy.rake.trim <- trimWeights(small.svy.rake, lower=0.3, upper=3,
                                  strict=TRUE) 

summary(weights(small.svy.rake.trim))

prop.table(survey::svytable(~sexo,design = small.svy.rake.trim))
prop.table(survey::svytable(~edad,design = small.svy.rake.trim))


```


* https://web.stanford.edu/~jhain/ebalancepage.html

```{r}
install.packages("ebal")
library("ebal")

treatment   <- c(rep(0,50),rep(1,30))
X           <- rbind(replicate(3,rnorm(50,0)),replicate(3,rnorm(30,.5)))
colnames(X) <- paste("x",1:3,sep="")

# entropy balancing
eb.out <- ebalance(Treatment=treatment,
                   X=X)
# means in treatment group data
apply(X[treatment==1,],2,mean)
# means in reweighted control group data
apply(X[treatment==0,],2,weighted.mean,w=eb.out$w)
# means in raw data control group data
apply(X[treatment==0,],2,mean)
```

