---
title: "Data preparation - Study 1"
author: "Julio Iturra"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output:
  bookdown::html_document2:
    number_sections: true
    toc: true
    toc_float:
        collapsed: false
    toc_depth: 2
    code_folding: "hide"
editor_options:
  chunk_output_type: console
---

# Setup

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE, 
                      cache = TRUE,
                      results = "hold")
options(scipen=999)
rm(list=ls())
options(knitr.kable.NA = '')
# .rs.restartR()
```

```{css, echo=FALSE}
# /* expandir el espacio del documento*/
body .main-container {
      max-width: 1600px !important;
      width: 1600px !important;
    }
#/* expandir width de la TOC*/
div.tocify {
    width: 22% !important;
    max-width: 331px !important;
    max-height: 102% !important;
}
```

```{r}
rm(list=ls())
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,       # Manipulacion de datos 
               haven,       # importar datos en .dta o .sav
               sjmisc,      # descriptivos y frecuencias
               sjPlot,      # tablas, plots y descriptivos
               sjlabelled,
               summarytools,# resumen de dataframe
               knitr,       # tablas kable
               kableExtra,  # tablas kable personalizadas
               ggplot2,     # plots
               corrplot,    # plot correlacion
               tibble,
               lavaan
               )

load(here::here("input/data/proc/study1.RData"))
data1 <- study_1 %>% 
  dplyr::select(-educ,-edmad,-edpad) %>%
  na.omit()
```



# Modelos

## Pol. Part

### Disruptive & Online {-}

```{r part-edpad, results='asis'}
rm(list=ls())
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,       # Manipulacion de datos 
               haven,       # importar datos en .dta o .sav
               sjmisc,      # descriptivos y frecuencias
               sjPlot,      # tablas, plots y descriptivos
               sjlabelled,
               summarytools,# resumen de dataframe
               knitr,       # tablas kable
               kableExtra,  # tablas kable personalizadas
               ggplot2,     # plots
               corrplot,    # plot correlacion
               tibble,
               lavaan
               )

load(here::here("input/data/proc/study1.RData"))
data1 <- study_1 %>% dplyr::select(-educ,-edmad,-edpad) %>% na.omit()

df <- data1 %>% select(psu,educyear,edmadyear,edpadyear,starts_with("onli")) %>% na.omit()
# skimr::skim(df)

cormat<- polycor::hetcor(data = df)
cormat$correlations
round(cormat$tests,5)
corrplot::corrplot.mixed(cormat$correlations)

m1a<- '
        # modelo de medicion
        disrup1a =~ mdis1a + bloq1a + raya1a + toma1a
        online1a =~ onli1a + post1a + come1a + segu1a
        
        # (1) modelo de regresion: PARTICIPACION DISRUPTIVA ____________________
        # efecto directo
        disrup1a ~ C1*edpadyear+B1A*educyear+B1B*conv1a+mujer+pospolcen+pospolizq+pospolind
        
        # efecto mediacion predictor sobre mediador (DECLARAR UNA VEZ)
        # educ padres sobre educacion hijos
        educyear ~ A1A*edpadyear+mujer+pospolcen+pospolizq+pospolind
        
        # educ padres sobre conversacion hijos
        conv1a ~ A1B*edpadyear+mujer+pospolcen+pospolizq+pospolind
        
        # efecto indirecto (A*B)
        # educpadres by educ-hijos (A1)
        ind_dis1_educ:= A1A*B1A 
        # educpadres by conversation (A2)
        ind_dis2_conv:= A1B*B1B

        # total effect
        tot_dis1_educ:= C1 + (A1A*B1A)
        tot_dis2_conv:= C1 + (A1B*B1B)
        
        # (2) modelo de regresion: PARTICIPACION ONLINE ________________________
        # efecto directo
        online1a ~ C2*edpadyear+B2A*educyear+B2B*conv1a+mujer+pospolcen+pospolizq+pospolind
        
        # efecto indirecto (A*B)
        # educpadres by educ-hijos (A2)
        ind_onl_educ:= A1A*B2A 
        # educpadres by conversation (A2)
        ind_onl2_conv:= A1B*B2B

        # total effect
        tot_onl1_educ:= C2 + (A1A*B2A)
        tot_onl2_conv:= C2 + (A1A*B2B)        
'


m2a <- stringr::str_replace_all(string = m1a,pattern = "1a",replacement = "2a")
m3a <- stringr::str_replace_all(string = m1a,pattern = "1a",replacement = "3a")
m4a <- stringr::str_replace_all(string = m1a,pattern = "1a",replacement = "4a")
m5a <- stringr::str_replace_all(string = m1a,pattern = "1a",replacement = "5a")

models <- c(m1a,m2a,m3a,m4a,m5a)

fits <- list()
for (i in 1:length(models)) {
    fits[[i]] <- lavaan::sem(model = models[[i]], data = data1,ordered = T)    
}

fit<- texreg::get.data(l = fits)
filt<- data.frame(coef=fit[[1]]@coef.names)

tabhux <- texreg::huxtablereg(fit,single.row = T)
tabhux2 <- dplyr::filter(tabhux,(grepl(' ~ ', V1)))
tabhux3 <- dplyr::filter(tabhux2,!(grepl('mujer', V1)))
tabhux4 <- dplyr::filter(tabhux3,!(grepl('pospol', V1)))
fitind <- tabhux %>% filter(V1 %in% c("cfi","tli","rmsea","nobs")) 

tabind_dis <- dplyr::filter(tabhux,(grepl('ind_dis', V1))) 
tabtot_dis <- dplyr::filter(tabhux,(grepl('tot_dis', V1)))

tabind_onl <- dplyr::filter(tabhux,(grepl('ind_onl', V1)))
tabtot_onl <- dplyr::filter(tabhux,(grepl('tot_onl', V1)))

coalesce_all_columns <- function(df) {
  tibble(
    V1 = df$V1[1],
    V2 = na.omit(df$V2),
    V3 = na.omit(df$V3),
    V4 = na.omit(df$V4),
    V5 = na.omit(df$V5),
    V6 = na.omit(df$V6)        
  )
}

#Participacion disruptiva
tabdis <- tabhux4 %>%  dplyr::filter((grepl('disrup', V1))) %>% 
  mutate(V1=stringr::str_replace_all(string = V1,
                                     pattern = "1a|2a|3a|4a|5a",
                                     replacement = "")) %>% 
  as.data.frame()
tabdis[tabdis==""] <- NA
tabdis <- tabdis %>%  group_by(V1) %>% do(coalesce_all_columns(.)) %>%  ungroup() %>% 
  rbind(tabind_dis,tabtot_dis,fitind) 

#Participacion online
tabonl <- tabhux4 %>%  dplyr::filter((grepl('online', V1))) %>% 
  mutate(V1=stringr::str_replace_all(string = V1,
                                     pattern = "1a|2a|3a|4a|5a",
                                     replacement = "")) %>% 
  as.data.frame()
tabonl[tabonl==""] <- NA  
tabonl <- tabonl %>%  group_by(V1) %>% do(coalesce_all_columns(.)) %>%  ungroup() %>% 
  rbind(tabind_dis,tabtot_dis,fitind)   

coef <- c("Conversation" ,
  "Years of education - father",
  "Years of education",
  "Ind: Education",
  "Ind: Conversation",
  "Total: Education",
  "Total: Conversation",
  "CFI",
  "RMSEA",
  "TLI",
  "N")

col <- c(" ",paste0("Model ",1:length(fits)))
tabdis$V1 <- coef 
kable(tabdis,format = "html",
      booktabs=T,
      row.names = F,
      caption = "Disruptive political participation, father education and conversation",
      col.names = col) %>% 
  kable_styling(full_width = F)
tabonl$V1 <- coef 
kable(tabonl,format = "html",
      booktabs=T,
      row.names = F,
      caption = "Online political participation, father education and conversation",
      col.names = col) %>% 
  kable_styling(full_width = F) %>% 
  row_spec(7,hline_after = T)
```

```{r part-edmad, results='asis'}
rm(list=ls())
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,       # Manipulacion de datos 
               haven,       # importar datos en .dta o .sav
               sjmisc,      # descriptivos y frecuencias
               sjPlot,      # tablas, plots y descriptivos
               sjlabelled,
               summarytools,# resumen de dataframe
               knitr,       # tablas kable
               kableExtra,  # tablas kable personalizadas
               ggplot2,     # plots
               corrplot,    # plot correlacion
               tibble,
               lavaan
               )

load(here::here("input/data/proc/study1.RData"))
data1 <- study_1 %>% dplyr::select(-educ,-edmad,-edpad) %>% na.omit()

m1a<- '
        # modelo de medicion
        disrup1a =~ mdis1a + bloq1a + raya1a + toma1a
        online1a =~ onli1a + post1a + come1a + segu1a
        
        # (1) modelo de regresion: PARTICIPACION DISRUPTIVA ____________________
        # efecto directo
        disrup1a ~ C1*edmadyear+B1A*educyear+B1B*conv1a+mujer+pospolcen+pospolizq+pospolind
        
        # efecto mediacion predictor sobre mediador (DECLARAR UNA VEZ)
        # educ padres sobre educacion hijos
        educyear ~ A1A*edmadyear+mujer+pospolcen+pospolizq+pospolind
        
        # educ padres sobre conversacion hijos
        conv1a ~ A1B*edmadyear+mujer+pospolcen+pospolizq+pospolind
        
        # efecto indirecto (A*B)
        # educpadres by educ-hijos (A1)
        ind_dis1_educ:= A1A*B1A 
        # educpadres by conversation (A2)
        ind_dis2_conv:= A1B*B1B

        # total effect
        tot_dis1_educ:= C1 + (A1A*B1A)
        tot_dis2_conv:= C1 + (A1B*B1B)
        
        # (2) modelo de regresion: PARTICIPACION ONLINE ________________________
        # efecto directo
        online1a ~ C2*edmadyear+B2A*educyear+B2B*conv1a+mujer+pospolcen+pospolizq+pospolind
        
        # efecto indirecto (A*B)
        # educpadres by educ-hijos (A2)
        ind_onl_educ:= A1A*B2A 
        # educpadres by conversation (A2)
        ind_onl2_conv:= A1B*B2B

        # total effect
        tot_onl1_educ:= C2 + (A1A*B2A)
        tot_onl2_conv:= C2 + (A1A*B2B)        
'


m2a <- stringr::str_replace_all(string = m1a,pattern = "1a",replacement = "2a")
m3a <- stringr::str_replace_all(string = m1a,pattern = "1a",replacement = "3a")
m4a <- stringr::str_replace_all(string = m1a,pattern = "1a",replacement = "4a")
m5a <- stringr::str_replace_all(string = m1a,pattern = "1a",replacement = "5a")

models <- c(m1a,m2a,m3a,m4a,m5a)

fits <- list()
for (i in 1:length(models)) {
    fits[[i]] <- lavaan::sem(model = models[[i]], data = data1,ordered = T)    
}

fit<- texreg::get.data(l = fits)
filt<- data.frame(coef=fit[[1]]@coef.names)

tabhux <- texreg::huxtablereg(fit,single.row = T)
tabhux2 <- dplyr::filter(tabhux,(grepl(' ~ ', V1)))
tabhux3 <- dplyr::filter(tabhux2,!(grepl('mujer', V1)))
tabhux4 <- dplyr::filter(tabhux3,!(grepl('pospol', V1)))
fitind <- tabhux %>% filter(V1 %in% c("cfi","tli","rmsea","nobs")) 

tabind_dis <- dplyr::filter(tabhux,(grepl('ind_dis', V1))) 
tabtot_dis <- dplyr::filter(tabhux,(grepl('tot_dis', V1)))

tabind_onl <- dplyr::filter(tabhux,(grepl('ind_onl', V1)))
tabtot_onl <- dplyr::filter(tabhux,(grepl('tot_onl', V1)))

coalesce_all_columns <- function(df) {
  tibble(
    V1 = df$V1[1],
    V2 = na.omit(df$V2),
    V3 = na.omit(df$V3),
    V4 = na.omit(df$V4),
    V5 = na.omit(df$V5),
    V6 = na.omit(df$V6)        
  )
}

#Participacion disruptiva
tabdis <- tabhux4 %>%  dplyr::filter((grepl('disrup', V1))) %>% 
  mutate(V1=stringr::str_replace_all(string = V1,
                                     pattern = "1a|2a|3a|4a|5a",
                                     replacement = "")) %>% 
  as.data.frame()
tabdis[tabdis==""] <- NA
tabdis <- tabdis %>%  group_by(V1) %>% do(coalesce_all_columns(.)) %>%  ungroup() %>% 
  rbind(tabind_dis,tabtot_dis,fitind) 

#Participacion online
tabonl <- tabhux4 %>%  dplyr::filter((grepl('online', V1))) %>% 
  mutate(V1=stringr::str_replace_all(string = V1,
                                     pattern = "1a|2a|3a|4a|5a",
                                     replacement = "")) %>% 
  as.data.frame()
tabonl[tabonl==""] <- NA  
tabonl <- tabonl %>%  group_by(V1) %>% do(coalesce_all_columns(.)) %>%  ungroup() %>% 
  rbind(tabind_dis,tabtot_dis,fitind)   

coef <- c("Conversation" ,
  "Years of education - mother",
  "Years of education",
  "Ind: Education",
  "Ind: Conversation",
  "Total: Education",
  "Total: Conversation",
  "CFI",
  "RMSEA",
  "TLI",
  "N")

col <- c(" ",paste0("Model ",1:length(fits)))
tabdis$V1 <- coef
kable(tabdis,format = "html",
      booktabs=T,
      row.names = F,
      caption = "Disruptive political participation, mother education and conversation",
      col.names = col) %>% 
  kable_styling(full_width = F)
tabonl$V1 <- coef
kable(tabonl,format = "html",
      booktabs=T,
      row.names = F,
      caption = "Online political participation, mother education and conversation",
      col.names = col) %>% 
  kable_styling(full_width = F) %>% 
  row_spec(7,hline_after = T)
```

```{r part-edavg, results='asis'}
rm(list=ls())
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,       # Manipulacion de datos 
               haven,       # importar datos en .dta o .sav
               sjmisc,      # descriptivos y frecuencias
               sjPlot,      # tablas, plots y descriptivos
               sjlabelled,
               summarytools,# resumen de dataframe
               knitr,       # tablas kable
               kableExtra,  # tablas kable personalizadas
               ggplot2,     # plots
               corrplot,    # plot correlacion
               tibble,
               lavaan
               )

load(here::here("input/data/proc/study1.RData"))
data1 <- study_1 %>% dplyr::select(-educ,-edmad,-edpad) %>% na.omit()

m1a<- '
        # modelo de medicion
        disrup1a =~ mdis1a + bloq1a + raya1a + toma1a
        online1a =~ onli1a + post1a + come1a + segu1a
        
        # (1) modelo de regresion: PARTICIPACION DISRUPTIVA ____________________
        # efecto directo
        disrup1a ~ C1*edparavg+B1A*educyear+B1B*conv1a+mujer+pospolcen+pospolizq+pospolind
        
        # efecto mediacion predictor sobre mediador (DECLARAR UNA VEZ)
        # educ padres sobre educacion hijos
        educyear ~ A1A*edparavg+mujer+pospolcen+pospolizq+pospolind
        
        # educ padres sobre conversacion hijos
        conv1a ~ A1B*edparavg+mujer+pospolcen+pospolizq+pospolind
        
        # efecto indirecto (A*B)
        # educpadres by educ-hijos (A1)
        ind_dis1_educ:= A1A*B1A 
        # educpadres by conversation (A2)
        ind_dis2_conv:= A1B*B1B

        # total effect
        tot_dis1_educ:= C1 + (A1A*B1A)
        tot_dis2_conv:= C1 + (A1B*B1B)
        
        # (2) modelo de regresion: PARTICIPACION ONLINE ________________________
        # efecto directo
        online1a ~ C2*edparavg+B2A*educyear+B2B*conv1a+mujer+pospolcen+pospolizq+pospolind
        
        # efecto indirecto (A*B)
        # educpadres by educ-hijos (A2)
        ind_onl_educ:= A1A*B2A 
        # educpadres by conversation (A2)
        ind_onl2_conv:= A1B*B2B

        # total effect
        tot_onl1_educ:= C2 + (A1A*B2A)
        tot_onl2_conv:= C2 + (A1A*B2B)        
'


m2a <- stringr::str_replace_all(string = m1a,pattern = "1a",replacement = "2a")
m3a <- stringr::str_replace_all(string = m1a,pattern = "1a",replacement = "3a")
m4a <- stringr::str_replace_all(string = m1a,pattern = "1a",replacement = "4a")
m5a <- stringr::str_replace_all(string = m1a,pattern = "1a",replacement = "5a")

models <- c(m1a,m2a,m3a,m4a,m5a)

fits <- list()
for (i in 1:length(models)) {
    fits[[i]] <- lavaan::sem(model = models[[i]], data = data1,ordered = T)    
}

fit<- texreg::get.data(l = fits)
filt<- data.frame(coef=fit[[1]]@coef.names)

tabhux <- texreg::huxtablereg(fit,single.row = T)
tabhux2 <- dplyr::filter(tabhux,(grepl(' ~ ', V1)))
tabhux3 <- dplyr::filter(tabhux2,!(grepl('mujer', V1)))
tabhux4 <- dplyr::filter(tabhux3,!(grepl('pospol', V1)))
fitind <- tabhux %>% filter(V1 %in% c("cfi","tli","rmsea","nobs")) 

tabind_dis <- dplyr::filter(tabhux,(grepl('ind_dis', V1))) 
tabtot_dis <- dplyr::filter(tabhux,(grepl('tot_dis', V1)))

tabind_onl <- dplyr::filter(tabhux,(grepl('ind_onl', V1)))
tabtot_onl <- dplyr::filter(tabhux,(grepl('tot_onl', V1)))

coalesce_all_columns <- function(df) {
  tibble(
    V1 = df$V1[1],
    V2 = na.omit(df$V2),
    V3 = na.omit(df$V3),
    V4 = na.omit(df$V4),
    V5 = na.omit(df$V5),
    V6 = na.omit(df$V6)        
  )
}

#Participacion disruptiva
tabdis <- tabhux4 %>%  dplyr::filter((grepl('disrup', V1))) %>% 
  mutate(V1=stringr::str_replace_all(string = V1,
                                     pattern = "1a|2a|3a|4a|5a",
                                     replacement = "")) %>% 
  as.data.frame()
tabdis[tabdis==""] <- NA
tabdis <- tabdis %>%  group_by(V1) %>% do(coalesce_all_columns(.)) %>%  ungroup() %>% 
  rbind(tabind_dis,tabtot_dis,fitind) 

#Participacion online
tabonl <- tabhux4 %>%  dplyr::filter((grepl('online', V1))) %>% 
  mutate(V1=stringr::str_replace_all(string = V1,
                                     pattern = "1a|2a|3a|4a|5a",
                                     replacement = "")) %>% 
  as.data.frame()
tabonl[tabonl==""] <- NA  
tabonl <- tabonl %>%  group_by(V1) %>% do(coalesce_all_columns(.)) %>%  ungroup() %>% 
  rbind(tabind_dis,tabtot_dis,fitind)   

coef <- c("Conversation" ,
  "Years of education - average",
  "Years of education",
  "Ind: Education",
  "Ind: Conversation",
  "Total: Education",
  "Total: Conversation",
  "CFI",
  "RMSEA",
  "TLI",
  "N")

col <- c(" ",paste0("Model ",1:length(fits)))
tabdis$V1 <- coef
kable(tabdis,format = "html",
      booktabs=T,
      row.names = F,
      caption = "Disruptive political participation, parental education and conversation",
      col.names = col) %>% 
  kable_styling(full_width = F)
tabonl$V1 <- coef
kable(tabonl,format = "html",
      booktabs=T,
      row.names = F,
      caption = "Online political participation, parental education and conversation",
      col.names = col) %>% 
  kable_styling(full_width = F) %>% 
  row_spec(7,hline_after = T)
```

### Voting behaviour {-}

```{r vot-edpad, results='asis'}
rm(list=ls())
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,       # Manipulacion de datos 
               haven,       # importar datos en .dta o .sav
               sjmisc,      # descriptivos y frecuencias
               sjPlot,      # tablas, plots y descriptivos
               sjlabelled,
               summarytools,# resumen de dataframe
               knitr,       # tablas kable
               kableExtra,  # tablas kable personalizadas
               ggplot2,     # plots
               texreg,
               mediation
               )

load(here::here("input/data/proc/study1.RData"))
data1 <- study_1 %>% 
  dplyr::select(-educ,-edmad,-edpad) %>% 
  dplyr::filter(votpr17 !=2 & votpleb !=2 & votcons !=2) %>%
  dplyr::select(mujer:conv5a,votpr17:vot2vue,
         educyear,edmadyear,edpadyear,edparavg,
         pospolcen,pospolizq,pospolind,pospol) %>% 
  mutate(conv1a=as_numeric(conv1a),
         conv3a=as_numeric(conv3a),
         conv4a=as_numeric(conv4a),
         conv5a=as_numeric(conv5a)) %>% 
  na.omit()

# view_df(data1)
# sjmisc::frq(data1$votpr17)
# sjmisc::frq(data1$votpleb)
# sjmisc::frq(data1$votcons)

# Hypothesis___________________________________________________________________
m1 <- "edpadyear+educyear+conv1a+mujer+pospol"#highschool
m2 <- "edpadyear+educyear+conv3a+mujer+pospol"# 2sem 2020
m3 <- "edpadyear+educyear+conv4a+mujer+pospol"# 1sem 2021
m4 <- "edpadyear+educyear+conv5a+mujer+pospol"# 2sem 2021

# Set the independent variables (IVs)
ivs1<- data1 %>% dplyr::select(votpr17) %>% names()        #highschool
ivs2<- data1 %>% dplyr::select(votpleb) %>% names()        # 2sem 2020
ivs3<- data1 %>% dplyr::select(votcons:votgobe) %>% names()# 1sem 2021
ivs4<- data1 %>% dplyr::select(votdipu:vot2vue) %>% names()# 2sem 2021

ivs <- c(ivs1,ivs2,ivs3,ivs4)

# Create the object for each model
models <- list()
for (i in ivs1) {
models[[i]] <- paste0(i,"~",m1)  
}

for (i in ivs2) {
models[[i]] <- paste0(i,"~",m2)  
}

for (i in ivs3) {
models[[i]] <- paste0(i,"~",m3)  
}

for (i in ivs4) {
models[[i]] <- paste0(i,"~",m4)  
}

# Estimate logit models
fits <- list()
for (i in ivs) {
  for (z in models[[i]]) {
    fits[[z]] <- glm(formula =z, data = data1,family = binomial(link="logit"))
  }
}
fit1 <- fits
# change model names within list
names(fit1) <- paste0(ivs)

# Tables_______________________________________________________________________
omit <- "(Intercept)|(mujer)|(pospol)"

# detail for subsections:
# https://stackoverflow.com/questions/69338331/r-markdown-create-section-headers-in-r-and-print-r-output-in-same-section


caption <- "Voting behaviour, father education and conversation"
htmlreg(l = fit1[names(fit1)[grepl("vot", names(fit1),"\n")]],
        omit.coef = omit,
        caption = caption,
        caption.above = T
        # reorder.coef = reorderc
        )

# Mediation analysis___________________________________________________________
mededuc1 <- "edpadyear+conv1a+mujer+pospol"#highschool
mededuc2 <- "edpadyear+conv3a+mujer+pospol"# 2sem 2020
mededuc3 <- "edpadyear+conv4a+mujer+pospol"# 1sem 2021
mededuc4 <- "edpadyear+conv5a+mujer+pospol"# 2sem 2021
mededuc <- c(mededuc1,mededuc2,mededuc3,mededuc4)

medconv1 <- "edpadyear+educyear+mujer+pospol"#highschool
medconv2 <- "edpadyear+educyear+mujer+pospol"# 2sem 2020
medconv3 <- "edpadyear+educyear+mujer+pospol"# 1sem 2021
medconv4 <- "edpadyear+educyear+mujer+pospol"# 2sem 2021
medconv <- c(medconv1,medconv2,medconv3,medconv4)

ivs1 <- c("educyear")
ivs2 <- c("conv1a","conv3a","conv4a","conv5a")

# Create the object for each model
lm.educ <- list()
for (i in ivs1) {
lm.educ[[i]] <- paste0(i,"~",mededuc)
}

lm.conv <- list()
for (i in ivs2) {
lm.conv[[i]] <- paste0(i,"~",medconv)
}


# Estimate OLS models: mediator~predictor
fit_educ <- list()
for (i in ivs1) {
  for (z in lm.educ[[i]]) {
    fit_educ[[z]] <- lm(formula =z, data = data1)
  }
}


fit_conv <- list()
for (i in ivs2) {
  for (z in lm.conv[[i]]) {
    fit_conv[[z]] <- lm(formula =z, data = data1)
  }
}

# change model names within list
names(fit_educ) <- paste0("ed_",ivs2)
names(fit_conv) <- paste0("co_",ivs2)


# Estimate mediation model_____________________________________________________

############################.
# mediated by Education    #
############################.
medieduc <- list()
for (i in c("votpr17")) {
  for (z in c("ed_conv1a")) {
medieduc[[i]]<- mediation::mediate(fit_educ[[z]],fit1[[i]], 
                                treat="edpadyear", mediator="educyear")    
  }
}

for (i in "votpleb") {
  for (z in "ed_conv3a") {
medieduc[[i]]<- mediation::mediate(fit_educ[[z]],fit1[[i]], 
                                treat="edpadyear", mediator="educyear")    
  }
}


for (i in c("votcons","votconv","votmuni","votgobe")) {
  for (z in "ed_conv4a") {
medieduc[[i]]<- mediation::mediate(fit_educ[[z]],fit1[[i]], 
                                treat="edpadyear", mediator="educyear")    
  }
}

for (i in c("votdipu","vot1vue","vot2vue")) {
  for (z in "ed_conv5a") {
medieduc[[i]]<- mediation::mediate(fit_educ[[z]],fit1[[i]],  
                                treat="edpadyear", mediator="educyear")    
  }
}


# extract the average mediation effects 
label1 <- 
  stringr::str_remove_all(string = sjlabelled::get_label(study_1[,names(medieduc)]),
                          pattern = "Vote: ")
df_mededuc.ind <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,  
  "var"=names(medieduc),
  "effect"="Indirect",  
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_mededuc.ind$effect.avg[[i]] <- medieduc[[i]][["d.avg"]]
  df_mededuc.ind$ci.lwr[[i]] <- medieduc[[i]][["d.avg.ci"]][1]
  df_mededuc.ind$ci.upr[[i]] <- medieduc[[i]][["d.avg.ci"]][2]  
  df_mededuc.ind$pval[[i]] <- medieduc[[i]][["d.avg.p"]]
  }

df_mededuc.dir <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,  
  "var"=names(medieduc),
  "effect"=rep("Direct",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_mededuc.dir$effect.avg[[i]] <- medieduc[[i]][["z.avg"]]
  df_mededuc.dir$ci.lwr[[i]] <- medieduc[[i]][["z.avg.ci"]][1]
  df_mededuc.dir$ci.upr[[i]] <- medieduc[[i]][["z.avg.ci"]][2]  
  df_mededuc.dir$pval[[i]] <- medieduc[[i]][["z.avg.p"]]
  }


df_mededuc.tot <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,  
  "var"=names(medieduc),
  "effect"=rep("Total",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_mededuc.tot$effect.avg[[i]] <- medieduc[[i]][["tau.coef"]]
  df_mededuc.tot$ci.lwr[[i]] <- medieduc[[i]][["tau.ci"]][1]
  df_mededuc.tot$ci.upr[[i]] <- medieduc[[i]][["tau.ci"]][2]  
  df_mededuc.tot$pval[[i]] <- medieduc[[i]][["tau.p"]]
  }

df_mededuc.prop <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,
  "var"=names(medieduc),
  "effect"=rep("Proportion",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_mededuc.prop$effect.avg[[i]] <- medieduc[[i]][["n.avg"]]
  df_mededuc.prop$ci.lwr[[i]] <- medieduc[[i]][["n.avg.ci"]][1]
  df_mededuc.prop$ci.upr[[i]] <- medieduc[[i]][["n.avg.ci"]][2]  
  df_mededuc.prop$pval[[i]] <- medieduc[[i]][["n.avg.p"]]
  }

df_mededuc <- bind_rows(df_mededuc.ind,df_mededuc.dir,df_mededuc.tot,df_mededuc.prop) %>% 
  arrange(id) %>% 
  mutate(sig=gtools::stars.pval(pval)) %>%
  dplyr::select(-"id",-"var")

colnames <- c(" ","Type","Effect","Lower CI","Upper CI","p-value","Sig.")
note <- "‘***’ p < 0.001 ‘**’ p < 0.01 ‘*’ p < 0.05 ‘.’ p < 0.1"
kable(df_mededuc,format = "html",digits = 3, col.names = colnames, 
      caption = "Mediated effect of Father Education by Education on Voting behaviour") %>% 
  kable_styling(full_width = F) %>% 
  collapse_rows(columns = 1) %>% 
footnote(general = note,footnote_as_chunk = T)   

############################.
# mediated by conversation #
############################.

mediconv <- list()
for (i in c("votpr17")) {
  for (z in c("co_conv1a")) {
mediconv[[i]]<- mediation::mediate(fit_conv[[z]],fit1[[i]], 
                                treat="edpadyear", mediator="conv1a")    
  }
}

for (i in "votpleb") {
  for (z in "co_conv3a") {
mediconv[[i]]<- mediation::mediate(fit_conv[[z]],fit1[[i]], 
                                treat="edpadyear", mediator="conv3a")    
  }
}


for (i in c("votcons","votconv","votmuni","votgobe")) {
  for (z in "co_conv4a") {
mediconv[[i]]<- mediation::mediate(fit_conv[[z]],fit1[[i]],
                                treat="edpadyear", mediator="conv4a")    
  }
}

for (i in c("votdipu","vot1vue","vot2vue")) {
  for (z in "co_conv5a") {
mediconv[[i]]<- mediation::mediate(fit_conv[[z]],fit1[[i]],
                                treat="edpadyear", mediator="conv5a")    
  }
}

# extract the average mediation effects 
df_medconv.ind <- data.frame(
  "id"=1:length(mediconv),
  "lab"= label1,    
  "var"=names(mediconv),
  "effect"="Indirect",  
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_medconv.ind$effect.avg[[i]] <- mediconv[[i]][["d.avg"]]
  df_medconv.ind$ci.lwr[[i]] <- mediconv[[i]][["d.avg.ci"]][1]
  df_medconv.ind$ci.upr[[i]] <- mediconv[[i]][["d.avg.ci"]][2]  
  df_medconv.ind$pval[[i]] <- mediconv[[i]][["d.avg.p"]]
  }

df_medconv.dir <- data.frame(
  "id"=1:length(mediconv),
  "lab"= label1,    
  "var"=names(mediconv),
  "effect"=rep("Direct",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_medconv.dir$effect.avg[[i]] <- mediconv[[i]][["z.avg"]]
  df_medconv.dir$ci.lwr[[i]] <- mediconv[[i]][["z.avg.ci"]][1]
  df_medconv.dir$ci.upr[[i]] <- mediconv[[i]][["z.avg.ci"]][2]  
  df_medconv.dir$pval[[i]] <- mediconv[[i]][["z.avg.p"]]
  }


df_medconv.tot <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,    
  "var"=names(medieduc),
  "effect"=rep("Total",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_medconv.tot$effect.avg[[i]] <- mediconv[[i]][["tau.coef"]]
  df_medconv.tot$ci.lwr[[i]] <- mediconv[[i]][["tau.ci"]][1]
  df_medconv.tot$ci.upr[[i]] <- mediconv[[i]][["tau.ci"]][2]  
  df_medconv.tot$pval[[i]] <- mediconv[[i]][["tau.p"]]
  }

df_medconv.prop <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,    
  "var"=names(medieduc),
  "effect"=rep("Proportion",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_medconv.prop$effect.avg[[i]] <- mediconv[[i]][["n.avg"]]
  df_medconv.prop$ci.lwr[[i]] <- mediconv[[i]][["n.avg.ci"]][1]
  df_medconv.prop$ci.upr[[i]] <- mediconv[[i]][["n.avg.ci"]][2]  
  df_medconv.prop$pval[[i]] <- mediconv[[i]][["n.avg.p"]]
  }

df_medconv <- bind_rows(df_medconv.ind,df_medconv.dir,df_medconv.tot,df_medconv.prop) %>% 
  arrange(id) %>% 
  mutate(sig=gtools::stars.pval(pval)) %>% 
  dplyr::select(-"id",-"var")

kable(df_medconv,format = "html",digits = 3,col.names = colnames, 
      caption = "Mediated effect of Father Education by Conversation on Voting behaviour") %>% 
  kable_styling(full_width = F) %>% 
  collapse_rows(columns = 1) %>% 
  footnote(general = note,footnote_as_chunk = T) 
```

```{r vot-edmad, results='asis'}
rm(list=ls())
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,       # Manipulacion de datos 
               haven,       # importar datos en .dta o .sav
               sjmisc,      # descriptivos y frecuencias
               sjPlot,      # tablas, plots y descriptivos
               sjlabelled,
               summarytools,# resumen de dataframe
               knitr,       # tablas kable
               kableExtra,  # tablas kable personalizadas
               ggplot2,     # plots
               corrplot,    # plot correlacion
               tibble,
               lavaan,
               texreg
               )

load(here::here("input/data/proc/study1.RData"))
data1 <- study_1 %>% 
  dplyr::select(-educ,-edmad,-edpad) %>% 
  dplyr::filter(votpr17 !=2 & votpleb !=2 & votcons !=2) %>%
  dplyr::select(mujer:conv5a,votpr17:vot2vue,
         educyear,edmadyear,edpadyear,edparavg,
         pospolcen,pospolizq,pospolind,pospol 
         ) %>% 
  dplyr::mutate(conv1a=as_numeric(conv1a),
         conv3a=as_numeric(conv3a),
         conv4a=as_numeric(conv4a),
         conv5a=as_numeric(conv5a)) %>% 
  na.omit()

# view_df(data1)

# sjmisc::frq(data1$votpr17)
# sjmisc::frq(data1$votpleb)
# sjmisc::frq(data1$votcons)

# Hypothesis___________________________________________________________________
m1 <- "edmadyear+educyear+conv1a+mujer+pospol"#highschool
m2 <- "edmadyear+educyear+conv3a+mujer+pospol"# 2sem 2020
m3 <- "edmadyear+educyear+conv4a+mujer+pospol"# 1sem 2021
m4 <- "edmadyear+educyear+conv5a+mujer+pospol"# 2sem 2021

hipotesis <- c(m1,m2,m3,m4)

# Set the independent variables (IVs)
ivs1<- data1 %>% dplyr::select(votpr17) %>% names()        #highschool
ivs2<- data1 %>% dplyr::select(votpleb) %>% names()        # 2sem 2020
ivs3<- data1 %>% dplyr::select(votcons:votgobe) %>% names()# 1sem 2021
ivs4<- data1 %>% dplyr::select(votdipu:vot2vue) %>% names()# 2sem 2021

ivs <- c(ivs1,ivs2,ivs3,ivs4)

# Create the object for each model
models <- list()
for (i in ivs1) {
models[[i]] <- paste0(i,"~",m1)  
}

for (i in ivs2) {
models[[i]] <- paste0(i,"~",m2)  
}

for (i in ivs3) {
models[[i]] <- paste0(i,"~",m3)  
}

for (i in ivs4) {
models[[i]] <- paste0(i,"~",m4)  
}

# Estimate logit models
fits <- list()
for (i in ivs) {
  for (z in models[[i]]) {
    fits[[z]] <- glm(formula =z, data = data1,family = "binomial")
  }
}
fit1 <- fits
# change model names within list
names(fit1) <- paste0(ivs)

# Tables_______________________________________________________________________
omit <- "(Intercept)|(mujer)|(pospol)"

# detail for subsections:
# https://stackoverflow.com/questions/69338331/r-markdown-create-section-headers-in-r-and-print-r-output-in-same-section



caption <- "Voting behaviour, mother education and conversation"
htmlreg(l = fit1[names(fit1)[grepl("vot", names(fit1),"\n")]],
        omit.coef = omit,
        caption = caption,
        caption.above = T
        # reorder.coef = reorderc
        )

# Mediation analysis___________________________________________________________
mededuc1 <- "edmadyear+conv1a+mujer+pospol"#highschool
mededuc2 <- "edmadyear+conv3a+mujer+pospol"# 2sem 2020
mededuc3 <- "edmadyear+conv4a+mujer+pospol"# 1sem 2021
mededuc4 <- "edmadyear+conv5a+mujer+pospol"# 2sem 2021
mededuc <- c(mededuc1,mededuc2,mededuc3,mededuc4)

medconv1 <- "edmadyear+educyear+mujer+pospol"#highschool
medconv2 <- "edmadyear+educyear+mujer+pospol"# 2sem 2020
medconv3 <- "edmadyear+educyear+mujer+pospol"# 1sem 2021
medconv4 <- "edmadyear+educyear+mujer+pospol"# 2sem 2021
medconv <- c(medconv1,medconv2,medconv3,medconv4)

ivs1 <- c("educyear")
ivs2 <- c("conv1a","conv3a","conv4a","conv5a")

# Create the object for each model
lm.educ <- list()
for (i in ivs1) {
lm.educ[[i]] <- paste0(i,"~",mededuc)
}

lm.conv <- list()
for (i in ivs2) {
lm.conv[[i]] <- paste0(i,"~",medconv)
}


# Estimate OLS models: mediator~predictor
fit_educ <- list()
for (i in ivs1) {
  for (z in lm.educ[[i]]) {
    fit_educ[[z]] <- lm(formula =z, data = data1)
  }
}


fit_conv <- list()
for (i in ivs2) {
  for (z in lm.conv[[i]]) {
    fit_conv[[z]] <- lm(formula =z, data = data1)
  }
}

# change model names within list
names(fit_educ) <- paste0("ed_",ivs2)
names(fit_conv) <- paste0("co_",ivs2)

# Estimate mediation model_____________________________________________________

############################.
# mediated by Education    #
############################.
medieduc <- list()
for (i in c("votpr17")) {
  for (z in c("ed_conv1a")) {
medieduc[[i]]<- mediation::mediate(fit_educ[[z]],fit1[[i]], 
                                treat="edmadyear", mediator="educyear")    
  }
}

for (i in "votpleb") {
  for (z in "ed_conv3a") {
medieduc[[i]]<- mediation::mediate(fit_educ[[z]],fit1[[i]], 
                                treat="edmadyear", mediator="educyear")    
  }
}


for (i in c("votcons","votconv","votmuni","votgobe")) {
  for (z in "ed_conv4a") {
medieduc[[i]]<- mediation::mediate(fit_educ[[z]],fit1[[i]], 
                                treat="edmadyear", mediator="educyear")    
  }
}

for (i in c("votdipu","vot1vue","vot2vue")) {
  for (z in "ed_conv5a") {
medieduc[[i]]<- mediation::mediate(fit_educ[[z]],fit1[[i]],  
                                treat="edmadyear", mediator="educyear")    
  }
}


# extract the average mediation effects 
label1 <- 
  stringr::str_remove_all(string = sjlabelled::get_label(study_1[,names(medieduc)]),
                          pattern = "Vote: ")

df_mededuc.ind <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,    
  "var"=names(medieduc),
  "effect"="Indirect",  
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_mededuc.ind$effect.avg[[i]] <- medieduc[[i]][["d.avg"]]
  df_mededuc.ind$ci.lwr[[i]] <- medieduc[[i]][["d.avg.ci"]][1]
  df_mededuc.ind$ci.upr[[i]] <- medieduc[[i]][["d.avg.ci"]][2]  
  df_mededuc.ind$pval[[i]] <- medieduc[[i]][["d.avg.p"]]
  }

df_mededuc.dir <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,  
  "var"=names(medieduc),
  "effect"=rep("Direct",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_mededuc.dir$effect.avg[[i]] <- medieduc[[i]][["z.avg"]]
  df_mededuc.dir$ci.lwr[[i]] <- medieduc[[i]][["z.avg.ci"]][1]
  df_mededuc.dir$ci.upr[[i]] <- medieduc[[i]][["z.avg.ci"]][2]  
  df_mededuc.dir$pval[[i]] <- medieduc[[i]][["z.avg.p"]]
  }


df_mededuc.tot <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,    
  "var"=names(medieduc),
  "effect"=rep("Total",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_mededuc.tot$effect.avg[[i]] <- medieduc[[i]][["tau.coef"]]
  df_mededuc.tot$ci.lwr[[i]] <- medieduc[[i]][["tau.ci"]][1]
  df_mededuc.tot$ci.upr[[i]] <- medieduc[[i]][["tau.ci"]][2]  
  df_mededuc.tot$pval[[i]] <- medieduc[[i]][["tau.p"]]
  }

df_mededuc.prop <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,    
  "var"=names(medieduc),
  "effect"=rep("Proportion",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_mededuc.prop$effect.avg[[i]] <- medieduc[[i]][["n.avg"]]
  df_mededuc.prop$ci.lwr[[i]] <- medieduc[[i]][["n.avg.ci"]][1]
  df_mededuc.prop$ci.upr[[i]] <- medieduc[[i]][["n.avg.ci"]][2]  
  df_mededuc.prop$pval[[i]] <- medieduc[[i]][["n.avg.p"]]
  }

df_mededuc <- bind_rows(df_mededuc.ind,df_mededuc.dir,df_mededuc.tot,df_mededuc.prop) %>% 
  arrange(id) %>% 
  mutate(sig=gtools::stars.pval(pval)) %>% 
  dplyr::select(-"id",-"var")

colnames <- c(" ","Type","Effect","Lower CI","Upper CI","p-value","Sig.")
note <- "‘***’ p < 0.001 ‘**’ p < 0.01 ‘*’ p < 0.05 ‘.’ p < 0.1"
kable(df_mededuc,format = "html",digits = 3, col.names = colnames,
      caption = "Mediated effect of Mother Education by Education on Voting behaviour") %>% 
  kable_styling(full_width = F) %>% 
  collapse_rows(columns = 1) %>% 
  footnote(general = note,footnote_as_chunk = T)   

############################.
# mediated by conversation #
############################.

mediconv <- list()
for (i in c("votpr17")) {
  for (z in c("co_conv1a")) {
mediconv[[i]]<- mediation::mediate(fit_conv[[z]],fit1[[i]], 
                                treat="edmadyear", mediator="conv1a")    
  }
}

for (i in "votpleb") {
  for (z in "co_conv3a") {
mediconv[[i]]<- mediation::mediate(fit_conv[[z]],fit1[[i]], 
                                treat="edmadyear", mediator="conv3a")    
  }
}


for (i in c("votcons","votconv","votmuni","votgobe")) {
  for (z in "co_conv4a") {
mediconv[[i]]<- mediation::mediate(fit_conv[[z]],fit1[[i]],
                                treat="edmadyear", mediator="conv4a")    
  }
}

for (i in c("votdipu","vot1vue","vot2vue")) {
  for (z in "co_conv5a") {
mediconv[[i]]<- mediation::mediate(fit_conv[[z]],fit1[[i]],
                                treat="edmadyear", mediator="conv5a")    
  }
}

# extract the average mediation effects 
df_medconv.ind <- data.frame(
  "id"=1:length(mediconv),
  "lab"= label1,  
  "var"=names(mediconv),
  "effect"="Indirect",  
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_medconv.ind$effect.avg[[i]] <- mediconv[[i]][["d.avg"]]
  df_medconv.ind$ci.lwr[[i]] <- mediconv[[i]][["d.avg.ci"]][1]
  df_medconv.ind$ci.upr[[i]] <- mediconv[[i]][["d.avg.ci"]][2]  
  df_medconv.ind$pval[[i]] <- mediconv[[i]][["d.avg.p"]]
  }

df_medconv.dir <- data.frame(
  "id"=1:length(mediconv),
  "lab"= label1,  
  "var"=names(mediconv),
  "effect"=rep("Direct",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_medconv.dir$effect.avg[[i]] <- mediconv[[i]][["z.avg"]]
  df_medconv.dir$ci.lwr[[i]] <- mediconv[[i]][["z.avg.ci"]][1]
  df_medconv.dir$ci.upr[[i]] <- mediconv[[i]][["z.avg.ci"]][2]  
  df_medconv.dir$pval[[i]] <- mediconv[[i]][["z.avg.p"]]
  }


df_medconv.tot <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,  
  "var"=names(medieduc),
  "effect"=rep("Total",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_medconv.tot$effect.avg[[i]] <- mediconv[[i]][["tau.coef"]]
  df_medconv.tot$ci.lwr[[i]] <- mediconv[[i]][["tau.ci"]][1]
  df_medconv.tot$ci.upr[[i]] <- mediconv[[i]][["tau.ci"]][2]  
  df_medconv.tot$pval[[i]] <- mediconv[[i]][["tau.p"]]
  }

df_medconv.prop <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,  
  "var"=names(medieduc),
  "effect"=rep("Proportion",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_medconv.prop$effect.avg[[i]] <- mediconv[[i]][["n.avg"]]
  df_medconv.prop$ci.lwr[[i]] <- mediconv[[i]][["n.avg.ci"]][1]
  df_medconv.prop$ci.upr[[i]] <- mediconv[[i]][["n.avg.ci"]][2]  
  df_medconv.prop$pval[[i]] <- mediconv[[i]][["n.avg.p"]]
  }

df_medconv <- bind_rows(df_medconv.ind,df_medconv.dir,df_medconv.tot,df_medconv.prop) %>% 
  arrange(id) %>% 
  mutate(sig=gtools::stars.pval(pval)) %>% 
  dplyr::select(-"id",-"var")

kable(df_medconv,format = "html",digits = 3,col.names = colnames, 
      caption = "Mediated effect of Mother Education by Conversation on Voting behaviour") %>% 
  kable_styling(full_width = F) %>% 
  collapse_rows(columns = 1) %>% 
  footnote(general = note,footnote_as_chunk = T)   
```

```{r vot-edavg, results='asis'}
rm(list=ls())
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,       # Manipulacion de datos 
               haven,       # importar datos en .dta o .sav
               sjmisc,      # descriptivos y frecuencias
               sjPlot,      # tablas, plots y descriptivos
               sjlabelled,
               summarytools,# resumen de dataframe
               knitr,       # tablas kable
               kableExtra,  # tablas kable personalizadas
               ggplot2,     # plots
               corrplot,    # plot correlacion
               tibble,
               lavaan,
               texreg 
               )

load(here::here("input/data/proc/study1.RData"))
data1 <- study_1 %>% 
  dplyr::select(-educ,-edmad,-edpad) %>% 
  dplyr::filter(votpr17 !=2 & votpleb !=2 & votcons !=2) %>%
  dplyr::select(mujer:conv5a,votpr17:vot2vue,
         educyear,edmadyear,edpadyear,edparavg,
         pospolcen,pospolizq,pospolind,pospol 
         ) %>% 
  dplyr::mutate(conv1a=as_numeric(conv1a),
         conv3a=as_numeric(conv3a),
         conv4a=as_numeric(conv4a),
         conv5a=as_numeric(conv5a)) %>% 
  na.omit()

# view_df(data1)

# sjmisc::frq(data1$votpr17)
# sjmisc::frq(data1$votpleb)
# sjmisc::frq(data1$votcons)

# Hypothesis___________________________________________________________________
m1 <- "edparavg+educyear+conv1a+mujer+pospol"#highschool
m2 <- "edparavg+educyear+conv3a+mujer+pospol"# 2sem 2020
m3 <- "edparavg+educyear+conv4a+mujer+pospol"# 1sem 2021
m4 <- "edparavg+educyear+conv5a+mujer+pospol"# 2sem 2021

hipotesis <- c(m1,m2,m3,m4)

# Set the independent variables (IVs)
ivs1<- data1 %>% dplyr::select(votpr17) %>% names()        #highschool
ivs2<- data1 %>% dplyr::select(votpleb) %>% names()        # 2sem 2020
ivs3<- data1 %>% dplyr::select(votcons:votgobe) %>% names()# 1sem 2021
ivs4<- data1 %>% dplyr::select(votdipu:vot2vue) %>% names()# 2sem 2021

ivs <- c(ivs1,ivs2,ivs3,ivs4)

# Create the object for each model
models <- list()
for (i in ivs1) {
models[[i]] <- paste0(i,"~",m1)  
}

for (i in ivs2) {
models[[i]] <- paste0(i,"~",m2)  
}

for (i in ivs3) {
models[[i]] <- paste0(i,"~",m3)  
}

for (i in ivs4) {
models[[i]] <- paste0(i,"~",m4)  
}

# Estimate logit models
fits <- list()
for (i in ivs) {
  for (z in models[[i]]) {
    fits[[z]] <- glm(formula =z, data = data1,family = "binomial")
  }
}
fit1 <- fits
# change model names within list
names(fit1) <- paste0(ivs)

# Tables_______________________________________________________________________
omit <- "(Intercept)|(mujer)|(pospol)"
# detail for subsections:
# https://stackoverflow.com/questions/69338331/r-markdown-create-section-headers-in-r-and-print-r-output-in-same-section

caption <- "Voting behaviour, parental education and conversation"
htmlreg(l = fit1[names(fit1)[grepl("vot", names(fit1),"\n")]],
        omit.coef = omit,
        caption = caption,
        caption.above = T
        # reorder.coef = reorderc
        )

# Mediation analysis___________________________________________________________
mededuc1 <- "edparavg+conv1a+mujer+pospol"#highschool
mededuc2 <- "edparavg+conv3a+mujer+pospol"# 2sem 2020
mededuc3 <- "edparavg+conv4a+mujer+pospol"# 1sem 2021
mededuc4 <- "edparavg+conv5a+mujer+pospol"# 2sem 2021
mededuc <- c(mededuc1,mededuc2,mededuc3,mededuc4)

medconv1 <- "edparavg+educyear+mujer+pospol"#highschool
medconv2 <- "edparavg+educyear+mujer+pospol"# 2sem 2020
medconv3 <- "edparavg+educyear+mujer+pospol"# 1sem 2021
medconv4 <- "edparavg+educyear+mujer+pospol"# 2sem 2021
medconv <- c(medconv1,medconv2,medconv3,medconv4)

ivs1 <- c("educyear")
ivs2 <- c("conv1a","conv3a","conv4a","conv5a")

# Create the object for each model
lm.educ <- list()
for (i in ivs1) {
lm.educ[[i]] <- paste0(i,"~",mededuc)
}

lm.conv <- list()
for (i in ivs2) {
lm.conv[[i]] <- paste0(i,"~",medconv)
}


# Estimate OLS models: mediator~predictor
fit_educ <- list()
for (i in ivs1) {
  for (z in lm.educ[[i]]) {
    fit_educ[[z]] <- lm(formula =z, data = data1)
  }
}


fit_conv <- list()
for (i in ivs2) {
  for (z in lm.conv[[i]]) {
    fit_conv[[z]] <- lm(formula =z, data = data1)
  }
}

# change model names within list
names(fit_educ) <- paste0("ed_",ivs2)
names(fit_conv) <- paste0("co_",ivs2)

# Estimate mediation model_____________________________________________________

############################.
# mediated by Education    #
############################.
medieduc <- list()
for (i in c("votpr17")) {
  for (z in c("ed_conv1a")) {
medieduc[[i]]<- mediation::mediate(fit_educ[[z]],fit1[[i]], 
                                treat="edparavg", mediator="educyear")    
  }
}

for (i in "votpleb") {
  for (z in "ed_conv3a") {
medieduc[[i]]<- mediation::mediate(fit_educ[[z]],fit1[[i]], 
                                treat="edparavg", mediator="educyear")    
  }
}


for (i in c("votcons","votconv","votmuni","votgobe")) {
  for (z in "ed_conv4a") {
medieduc[[i]]<- mediation::mediate(fit_educ[[z]],fit1[[i]], 
                                treat="edparavg", mediator="educyear")    
  }
}

for (i in c("votdipu","vot1vue","vot2vue")) {
  for (z in "ed_conv5a") {
medieduc[[i]]<- mediation::mediate(fit_educ[[z]],fit1[[i]],  
                                treat="edparavg", mediator="educyear")    
  }
}


# extract the average mediation effects 
label1 <- 
  stringr::str_remove_all(string = sjlabelled::get_label(study_1[,names(medieduc)]),
                          pattern = "Vote: ")

df_mededuc.ind <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,  
  "var"=names(medieduc),
  "effect"="Indirect",  
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_mededuc.ind$effect.avg[[i]] <- medieduc[[i]][["d.avg"]]
  df_mededuc.ind$ci.lwr[[i]] <- medieduc[[i]][["d.avg.ci"]][1]
  df_mededuc.ind$ci.upr[[i]] <- medieduc[[i]][["d.avg.ci"]][2]  
  df_mededuc.ind$pval[[i]] <- medieduc[[i]][["d.avg.p"]]
  }

df_mededuc.dir <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,  
  "var"=names(medieduc),
  "effect"=rep("Direct",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_mededuc.dir$effect.avg[[i]] <- medieduc[[i]][["z.avg"]]
  df_mededuc.dir$ci.lwr[[i]] <- medieduc[[i]][["z.avg.ci"]][1]
  df_mededuc.dir$ci.upr[[i]] <- medieduc[[i]][["z.avg.ci"]][2]  
  df_mededuc.dir$pval[[i]] <- medieduc[[i]][["z.avg.p"]]
  }


df_mededuc.tot <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,  
  "var"=names(medieduc),
  "effect"=rep("Total",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_mededuc.tot$effect.avg[[i]] <- medieduc[[i]][["tau.coef"]]
  df_mededuc.tot$ci.lwr[[i]] <- medieduc[[i]][["tau.ci"]][1]
  df_mededuc.tot$ci.upr[[i]] <- medieduc[[i]][["tau.ci"]][2]  
  df_mededuc.tot$pval[[i]] <- medieduc[[i]][["tau.p"]]
  }

df_mededuc.prop <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,  
  "var"=names(medieduc),
  "effect"=rep("Proportion",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_mededuc.prop$effect.avg[[i]] <- medieduc[[i]][["n.avg"]]
  df_mededuc.prop$ci.lwr[[i]] <- medieduc[[i]][["n.avg.ci"]][1]
  df_mededuc.prop$ci.upr[[i]] <- medieduc[[i]][["n.avg.ci"]][2]  
  df_mededuc.prop$pval[[i]] <- medieduc[[i]][["n.avg.p"]]
  }

df_mededuc <- bind_rows(df_mededuc.ind,df_mededuc.dir,df_mededuc.tot,df_mededuc.prop) %>% 
  arrange(id) %>% 
  mutate(sig=gtools::stars.pval(pval)) %>% 
  dplyr::select(-"id",-"var")



colnames <- c(" ","Type","Effect","Lower CI","Upper CI","p-value","Sig.")
note <- "‘***’ p < 0.001 ‘**’ p < 0.01 ‘*’ p < 0.05 ‘.’ p < 0.1"
kable(df_mededuc,format = "html",digits = 3,col.names = colnames, 
      caption = "Mediated effect of Parental Education by Education on Voting behaviour") %>% 
  kable_styling(full_width = F) %>% 
  collapse_rows(columns = 1) %>% 
  footnote(general = note,footnote_as_chunk = T)

############################.
# mediated by conversation #
############################.

mediconv <- list()
for (i in c("votpr17")) {
  for (z in c("co_conv1a")) {
mediconv[[i]]<- mediation::mediate(fit_conv[[z]],fit1[[i]], 
                                treat="edparavg", mediator="conv1a")    
  }
}

for (i in "votpleb") {
  for (z in "co_conv3a") {
mediconv[[i]]<- mediation::mediate(fit_conv[[z]],fit1[[i]], 
                                treat="edparavg", mediator="conv3a")    
  }
}


for (i in c("votcons","votconv","votmuni","votgobe")) {
  for (z in "co_conv4a") {
mediconv[[i]]<- mediation::mediate(fit_conv[[z]],fit1[[i]],
                                treat="edparavg", mediator="conv4a")    
  }
}

for (i in c("votdipu","vot1vue","vot2vue")) {
  for (z in "co_conv5a") {
mediconv[[i]]<- mediation::mediate(fit_conv[[z]],fit1[[i]],
                                treat="edparavg", mediator="conv5a")    
  }
}

# extract the average mediation effects 
df_medconv.ind <- data.frame(
  "id"=1:length(mediconv),
  "lab"= label1,  
  "var"=names(mediconv),
  "effect"="Indirect",  
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_medconv.ind$effect.avg[[i]] <- mediconv[[i]][["d.avg"]]
  df_medconv.ind$ci.lwr[[i]] <- mediconv[[i]][["d.avg.ci"]][1]
  df_medconv.ind$ci.upr[[i]] <- mediconv[[i]][["d.avg.ci"]][2]  
  df_medconv.ind$pval[[i]] <- mediconv[[i]][["d.avg.p"]]
  }

df_medconv.dir <- data.frame(
  "id"=1:length(mediconv),
  "lab"= label1,  
  "var"=names(mediconv),
  "effect"=rep("Direct",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_medconv.dir$effect.avg[[i]] <- mediconv[[i]][["z.avg"]]
  df_medconv.dir$ci.lwr[[i]] <- mediconv[[i]][["z.avg.ci"]][1]
  df_medconv.dir$ci.upr[[i]] <- mediconv[[i]][["z.avg.ci"]][2]  
  df_medconv.dir$pval[[i]] <- mediconv[[i]][["z.avg.p"]]
  }


df_medconv.tot <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,  
  "var"=names(medieduc),
  "effect"=rep("Total",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_medconv.tot$effect.avg[[i]] <- mediconv[[i]][["tau.coef"]]
  df_medconv.tot$ci.lwr[[i]] <- mediconv[[i]][["tau.ci"]][1]
  df_medconv.tot$ci.upr[[i]] <- mediconv[[i]][["tau.ci"]][2]  
  df_medconv.tot$pval[[i]] <- mediconv[[i]][["tau.p"]]
  }

df_medconv.prop <- data.frame(
  "id"=1:length(medieduc),
  "lab"= label1,  
  "var"=names(medieduc),
  "effect"=rep("Proportion",9),
  "effect.avg"=NA,
  "ci.lwr"=NA,
  "ci.upr"=NA,
  "pval"=NA)

for (i in 1:9) {
  df_medconv.prop$effect.avg[[i]] <- mediconv[[i]][["n.avg"]]
  df_medconv.prop$ci.lwr[[i]] <- mediconv[[i]][["n.avg.ci"]][1]
  df_medconv.prop$ci.upr[[i]] <- mediconv[[i]][["n.avg.ci"]][2]  
  df_medconv.prop$pval[[i]] <- mediconv[[i]][["n.avg.p"]]
  }

df_medconv <- bind_rows(df_medconv.ind,df_medconv.dir,df_medconv.tot,df_medconv.prop) %>% 
  arrange(id) %>% 
  mutate(sig=gtools::stars.pval(pval)) %>% 
  dplyr::select(-"id",-"var")

kable(df_medconv,format = "html",digits = 3, col.names = colnames,
      caption = "Mediated effect of Parental Education by Conversation on Voting behaviour") %>% 
  kable_styling(full_width = F) %>% 
  collapse_rows(columns = 1) %>% 
  footnote(general = note,footnote_as_chunk = T)  
```

